Makefile, go.mod, go.sum, storage/sql.go, storage/sql_test.go
Adds makefile to support running postgres in docker and a test that checks the names
and column types of all expected tables.
=> feat: add test for create schema

lens/lotus/ctxStore.go, services/processor/processor.go, services/processor/publisher.go, services/processor/scheduler.go, services/processor/tasks/miner/miner.go
prevents tasks from blocking on publish
=> polish(publisher): receive publish operations on channel

go.sum, model/actors/miner/power.go, model/actors/miner/precommit.go, model/actors/miner/sector.go, model/actors/miner/state.go, model/actors/miner/task.go, model/blocks/drand.go, model/blocks/header.go, model/blocks/parent.go, model/blocks/synced.go, services/indexer/types.go, storage/sql.go
Correctly handles commit and rollback cases for errors that we not handled before. Thank you for the prompt to use this pattern @iand!
=> fix(model): replace BeginContext with RunInTransaction

model/actors/market/dealproposal.go, model/actors/market/dealstate.go, model/actors/market/task.go, model/genesis/task.go, services/processor/scheduler.go, services/processor/tasks/genesis/genesis.go, services/processor/tasks/market/market.go, services/processor/tasks/miner/miner.go, storage/sql.go
- process the market actors deal states and propols
- add handling for market actor processing in genesis task
to follow #8
=> feat(task): add market actor task

model/messages/blockmessage.go, model/messages/message.go, model/messages/receipt.go, model/messages/task.go, run.go, services/indexer/types.go, services/processor/processor.go, services/processor/scheduler.go, services/processor/tasks/message/message.go, storage/sql.go
- process messages
- process message block inclusions
- process receipts
=> feat(task): implement message processing task

model/actors/power/chainpower.go, services/processor/scheduler.go, services/processor/tasks/power/power.go, storage/sql.go
Need to wait for other inflight items to land before finishing this since we will want to pull out genesis state and that's done in #8
=> feat(task): add power actor processing task

go.mod, model/actors/common/actors.go, model/actors/common/task.go, model/actors/init/idaddress.go, model/genesis/task.go, services/processor/processor.go, services/processor/scheduler.go, services/processor/tasks/common/actor.go, services/processor/tasks/genesis/genesis.go, services/processor/tasks/init/init_actor.go, services/processor/tasks/market/market.go, storage/sql.go
Implements common actor processing.
=> feat(task): add actor, actor-state, and init actor processing

docker-compose.yml, services/indexer/indexer.go, services/indexer/indexer_test.go, storage/sql.go
Initial implementation of a test for indexing the chain. I plan to generalise this and move into a separate `testutil` package as I start adding tests for the various tasks.
=> feat: add tests for indexer

go.sum, services/processor/scheduler.go
Allow redis to be configured with env vars.
=> polish(redis): configure redis with env vars

main.go, run.go, storage/sql.go
provide a CLI flag and environment variable to set postgres pool size
set default as 75
=> pg: configurable pool size

Dockerfile, Makefile
A PR which applies the pattern recommended in https://github.com/filecoin-project/sentinel/pull/149#issuecomment-697990220
=> chore: Remove sentinel prefix for local dev use

.circleci/config.yml, scripts/push-docker-tags.sh
this repo is now set to build PRs only
remove branch filter so PRs will build docker images for testing purposes
=> remove branch filter

tasks/actorstate/reward.go
Consume the new lotus actor interfaces in reward actor.
=> refactor(task): reward task uses lotus interface

go.sum, tasks/actorstate/actorstate_test.go, tasks/actorstate/power_test.go, tasks/actorstate/reward_test.go
Note that this branched from #81
=> chore: add tests for reward and power actor state extracters

go.sum, tasks/indexer/blockdata.go
=> fix: remove errgrp from UnindexedBlockData persist

tasks/actorstate/actor.go, tasks/actorstate/actorstate.go
Last time I looked builtin2 did this for us but that seems to have disappeared.
=> get actor name for both versions of specs-actors

model/messages/parsedmessage.go, storage/migrations/13_parsed_message.go, tasks/message/message.go
=> include height with parsed messages

go.mod, lens/lotusrepo/repo.go, model/messages/parsedmessage.go, storage/migrations/13_parsed_message.go, tasks/message/message.go
* fills in missing modules in the repo lens chainstore / state manager apis
* catches panics possible in parsing messages
* makes message parsing less expensive api call
=> Fix issues in repo lens and message parsing

go.mod, go.sum
=> bump statediff to v0.0.7

build/grafana/provisioning/dashboards/dashboard-visor-processing.json
This is the wholesale export of the dashboard...I can filter changes down to just the query fixes if required.
Also, please can I get write access to this repo?
=> fix: visor_processing_stats queries for Visor processing dash

build/grafana/provisioning/dashboards/dashboard-visor-processing.json
Panels are added to the dashboard if there are tag values for them in the visor_processing_stats.tag column.
=> feat: add dynamic panel creation based on tags

lens/lotusrepo/repo.go
=> open lotusrepo lens read only

tasks/message/message.go
=> continue message parsing task when cbor parse fails

commands/run.go, schedule/scheduler.go
This is a re-creation of https://github.com/filecoin-project/sentinel-visor/pull/200 but to a hotfix branch
=> Adds an option to exit on failure.

commands/run.go, commands/run_test.go
=> fix: fix overflow bug when dividing height range

.circleci/config.yml, storage/migrations/17_chainvis_views_not_materialized.go
Make existing materialized views for ChainVis project into basic views.
=> fix: Make ChainVis into basic views

model/actors/multisig/task.go, model/genesis/task.go, tasks/actorstate/genesis.go
Hit when manually testing, I had previously made incorrect casting on the MultisigTaskResult type in the genesis processor.
=> fix: panic in multisig genesis task casting

go.mod, go.sum, tasks/actorstate/init.go
closes #226. I have manually tested this change to confirm that it works locally.
=> polish: use new init actor diffing logic

commands/run.go
Extracted from iand/beefy branch where I have been using this for a while. Ensures the context used to run queries is cancelled properly when the process exits.
=> fix: gracefully disconnect from postgres on exit

storage/sql.go
need to register the model to use it.
=> fix: missed while closing #201

tasks/message/message.go
=> polish: Avoid duplicate work when reading receipts

commands/run.go, go.mod, go.sum, tasks/indexer/chainhistoryindexer.go, tasks/indexer/chainhistoryindexer_test.go
Extracted from iand/beefy branch
=> feat: limit history indexer by height

tasks/actorstate/actorstate_test.go, tasks/actorstate/market_test.go, tasks/actorstate/power_test.go, tasks/actorstate/reward_test.go
This PR does the following:
- Moves tests in actorstate package to actorstate_test package
- Implements power actor test for claim extraction.
=> test: power actor claim extration test

tasks/actorstate/actorstate_test.go, tasks/actorstate/multisig_test.go
adds test coverage for multisig actor extraction. Extractor code has 84% coverage.
=> test: add multisig actor extractor tests

go.mod, go.sum, tasks/actorstate/actorstate_test.go, tasks/actorstate/init.go, tasks/actorstate/init_test.go
adds init actor extraction test coverage and fixes #262
=> test: add init actor extractor tests

tasks/message/message.go
=> fix: totalGasLimit and totalUniqueGasLimit are correct

go.mod, lens/carrepo/carrepo.go, lens/carrepo/proxystore.go, lens/lotus/lotus.go, lens/lotusrepo/repo.go, lens/sqlrepo/repo.go, model/actors/miner/currentdeadline.go, model/actors/miner/feedebt.go, model/actors/miner/precommit.go, model/actors/miner/sector.go, model/actors/miner/sectordeals.go, model/actors/miner/sectorevents.go, model/actors/miner/sectorposts.go, model/actors/power/claimedpower.go, model/chain/economics.go, model/derived/gasoutputs.go, model/messages/gaseconomy.go, model/visor/processing.go, model/visor/stats.go, schedule/scheduler.go, storage/sql_test.go, tasks/actorstate/actorstate.go, tasks/actorstate/actorstate_test.go, tasks/actorstate/genesis_test.go, tasks/actorstate/miner.go, tasks/actorstate/multisig.go, tasks/actorstate/power.go, tasks/indexer/chainheadindexer_test.go, tasks/indexer/chainhistoryindexer_test.go, tasks/message/message.go
No more linting emails, yay!
On approval I will squish and merge, commits were made separately in case I broke something while completing this.
closes #182
=> Fix all the linting errors

README.md
I spent the afternoon trying to get the tests running 🥲 These instructions are specific to macOS but I guess better than nothing.
=> docs: expand getting started guide and add running tests section

model/actors/miner/sectordeals.go, storage/migrations/23_miner_sector_deals_pk.go
Fixes https://github.com/filecoin-project/sentinel-visor/issues/280
=> fix(schema): fix primary key for miner_sector_deals table

.circleci/config.yml, .codecov.yml, Makefile
=> Run full testing suite in CI with code coverage

Makefile, go.mod, go.sum, tasks/actorstate/actor_test.go, tasks/actorstate/actorstate_test.go
- close #283
update Makefile such that `make test` "just works"... I hate the sleep but I don't know of any other way aside from removing postgres from unit testing.
also fixes linting errors that crept in
=> test(actorstate): unit test actorstate actor task

chain/indexer.go, metrics/metrics.go
Also add a view that counts the total number of api requests per task
=> feat: record metrics for watch and walk commands

chain/actor.go
As per the recent analysis of API usage this change saves us over 9000 roundtrips to lotus with a corresponding performance gain.
=> perf: replace local state diffing with StateChangeActors API method

storage/sql.go, storage/sql_test.go
Fixes https://github.com/filecoin-project/sentinel-visor/issues/307
=> fix: reject names that exceed maximum postgres name length

.circleci/config.yml, main.go
Reasoning behind change is in #347
=> feat: remove default value for --db parameter

.circleci/config.yml, CHANGELOG.md, Dockerfile.dev, go.mod, go.sum
Includes:
- building dev docker image
- CHANGELOG update
- update latest go.mod/sum
=> Release v0.4.0

storage/csv.go, storage/csv_test.go
Nil JSON values should be encoded as lower-case `null` in the CSV output, but other nil values should remain uppercase
Slices and other non-scalar types are automatically inferred to be stored as JSON by go-pg so we can use that to automatically encode. However `string` types that have the `type:jsonb` annotation in our models refer to values that have already been encoded as JSON, so the CSV output needs to avoid encoding them again.
=> fix: improve inferred json encoding for csv output

storage/migrations/27_table_and_column_comments.go
Documentation for visor tables and their columns.
resolves #223
=> feat: table and column comments

Makefile, README.md, docs/migrations.md, docs/release_management.md
Documentation of the release process I follow for `visor` so others may participate.
=> docs: Add release process details and workflow

commands/setup.go, commands/walk.go, commands/watch.go, main.go
- Dedupe code signal handler to cancel the context, now lives in main
- Remove unused code
=> chore: remove some dead code and dedup some other code

chain/indexer.go, vector/runner.go
=> fix(indexer): wait for persist routines to complete in Close

chain/watcher.go, metrics/metrics.go
Gives us more visibility about whether visor is seeing any tipsets arrive on the chain
=> feat: record tipset cache metrics during watch

.circleci/config.yml
Its been timing out a lot lately.. :disappointed:
=> chore: increase linter timout in ci

commands/walk.go, commands/watch.go
=> polish(lily): add job name flag

chain/walker.go, chain/watcher.go, lens/lily/struct.go, schedule/scheduler.go
=> polish(job): print job type, params, and errors in list

tasks/actorstate/miner.go
=> Track info for extended sectors

commands/watch.go
This is for the single-run watch command. Fixes an issue where no events were sent to indexer since channel was nil. Also fixes a potential panic condition where the notifier is cancelled and channel is closed but events are still being sent to the channel.
=> fix: ensure event channel is initialised before watch starts

chain/indexer.go, go.mod, go.sum, tasks/actorstate/account.go, tasks/actorstate/actorstate.go, tasks/actorstate/actorstate_test.go, tasks/actorstate/init.go, tasks/actorstate/init_test.go, tasks/actorstate/market.go, tasks/actorstate/miner.go, tasks/actorstate/multisig.go, tasks/actorstate/multisig_test.go, tasks/actorstate/power.go, tasks/actorstate/power_test.go, tasks/actorstate/reward.go, tasks/actorstate/reward_test.go, tasks/actorstate/task.go, tasks/msapprovals/msapprovals.go
Merge after v0.6.0 is tagged
This is just a preliminary integration with the v4 types, will need another update once actors v4 is released
=> feat: upgrade to actors v4

.circleci/config.yml
Unfortunately makes builds a lot slower, but more reliable
=> chore: add circleci step to test docker build

schedule/scheduler.go
=> fix(scheduler): deadlock on job specific lock in start

commands/util/rpc.go, lens/lily/api.go, lens/lily/struct.go, main.go
- allows for further control of the visor daemon
=> polish(cli): import lotus commands

CHANGELOG.md
Assumes #494 and #490 are merged
=> Release notes for v0.6.2

schedule/scheduler.go
=> fix(scheduler): allow scheduler to exit if scheduled jobs are complete

commands/client.go, commands/job.go, commands/sync.go, commands/util/rpc.go, commands/wait.go, lens/lily/api.go, lens/lily/impl.go, lens/lily/struct.go, main.go
Based on #499. Similar to Lotus implementation but with a configurable timeout.
=> feat: add wait-api command to wait for the visor api to come online

commands/daemon.go, config/config.go, storage/catalog.go
This allows the specification of connection information without embedding secrets in config files.
=> feat: allow database urls to use environment variables in config

model/actors/miner/minerinfo.go, schemas/v0/29_miner_info_sector_size.go, tasks/actorstate/miner.go
- closes #523
I've tested the change locally and confirmed the migration and task wae.
=> fix(miner_info): track miner sector size

chain/actors/builtin/miner/diff.go, chain/indexer.go, tasks/actorstate/miner.go, tasks/actorstate/task.go, tasks/blocks/task.go, tasks/chaineconomics/economics.go, tasks/chaineconomics/economics_test.go, tasks/messages/message.go, tasks/msapprovals/msapprovals.go
Adds more tracing calls for finding performance bottlenecks.
=> polish(tracing): add more tracing calls to critial path

chain/indexer.go, chain/util.go
optimizes StateChangedActors by using the hamt diffign logic falling back to the lotus method when required, see code comments for specifics.
=> feat(statetree): implement optimized state tree diffing

CHANGELOG.md
=> Release notes for version 0.6.7

README.md, go.mod, go.sum
Can build and run visor from my M1-Based MacBook, updates the README.md with steps to do so.
=> feat(build): support building and executing on M1-based Macs

chain/indexer.go, chain/util.go
=> deps(statetree): suppoort StateTreeVersion4

tasks/actorstate/init.go, tasks/actorstate/init_test.go
=> fix: ensure id_addresses contains height

Makefile, chain/walker_test.go, chain/watcher_test.go, go.mod, go.sum, main.go, tasks/actorstate/genesis_test.go, testutil/lens.go
closes #418 
Verified this runs as expected locally against the calibration network.
=> build(devnet): support building visor for devnets

chain/actors/builtin/miner/diff.go
found this while processing calibration.
=> fix(miner_diff): better errors, equals method, correct cid

commands/net.go, lens/lily/api.go, lens/lily/impl.go, lens/lily/struct.go, main.go
Ported from Lotus with some cosmetic tweaks
=> feat: add net commands for inspecting daemon connectivity

go.mod, go.sum
- fixes #564
relevant PR in go-amt-ipld: https://github.com/filecoin-project/go-amt-ipld/pull/56/files
=> fix(amt-diff): update amt package with diffing fix

commands/client.go, commands/daemon.go
=> fix(api): add usage for --api flag

tasks/messages/fcjson/marshal.go
=> feat(bf): decode message bitfields to json

.circleci/config.yml
=> ci(cache): cache vectors

chain/indexer.go
=> fix: skip actor and message tasks if tipset is not direct child of parent

chain/walker_test.go, chain/watcher_test.go, go.mod, go.sum, testutil/lens.go
=> deps(lotus): upgrade to lotus@v1.11.0

storage/migrate.go, storage/sql.go
=> fix(migration): use schema config for migrations

lens/lily/impl.go
=> fix(internal-msg): correctly handle error

chain/indexer.go, model/chain/consensus.go, model/consensus/consensus.go, schemas/v1/1_chainconsensus.go, tasks/consensus/task.go
=> feat(task): implement consensus task

chain/util.go, commands/util.go, commands/vector.go, commands/walk.go
Fixes https://github.com/filecoin-project/sentinel-visor/issues/616 and #593
=> fix: replace current epoch estimation with new function

commands/daemon.go, commands/help.go, commands/migrate.go, commands/run.go, commands/vector.go, main.go
Adds documentation for:
- an overview topic
- tasks
- monitoring
- daemon command
- run command (for standalone jobs)
=> feat: revamp help command and add topic based help text

chain/actors/adt/adt.go, chain/actors/builtin/verifreg/actor.go.template, chain/actors/builtin/verifreg/diff.go, chain/actors/builtin/verifreg/state.go.template, chain/actors/builtin/verifreg/v0.go, chain/actors/builtin/verifreg/v2.go, chain/actors/builtin/verifreg/v3.go, chain/actors/builtin/verifreg/v4.go, chain/actors/builtin/verifreg/v5.go, chain/actors/builtin/verifreg/verifreg.go, chain/indexer.go, model/actors/verifreg/state.go, schemas/v1/2_verifreg.go, tasks/actorstate/verifreg.go
- define task for tracking verifreg actor
- define actor shim with codegen and diffing logic for verifreg actor
- define sql migration for new task tables
=> feat(veri): implement verifreg diff methods and update shims

commands/chain.go, lens/lily/api.go, lens/lily/struct.go, main.go
=> chore(cli): implement chain reading methods

chain/indexer.go, lens/interface.go, model/actors/common/actors.go, tasks/actorstate/actor.go, tasks/actorstate/actorstate.go, tasks/actorstate/task.go
Payment Channel actors delete themselves when collected.
Fixes #662
=> fix: avoid reading state of deleted actors

README.md
ssh does not clone anonymously
=> Fix clone string

.circleci/config.yml, README.md, commands/daemon.go, commands/init.go, commands/migrate.go, config/config.go
=> chore(repo): default to ~/.lily repo

chain/indexer.go
=> fix: record internal message start and end time

tasks/messages/message_test.go, tasks/messages/messageparams.go
=> fix(task): implement method table for account actor

lens/lily/impl.go
To assist with https://github.com/filecoin-project/lily/issues/720
=> chore: wrap error from failed execution traces

storage/sql_test.go
=> fix: increase database wait time for tests

tasks/messages/message.go
=> fix(messages): don't report errors for messages with invalid method

tasks/messages/message_test.go, tasks/messages/messageparams.go
=> fix(message): message task tolerates unexpected params

tasks/messages/message.go
=> fix: ignore message parse errors for failed messages with unknown actor addresses

chain/fill.go, chain/find.go, chain/walker.go, chain/watcher.go, commands/job.go, lens/lily/api.go, lens/lily/impl.go, lens/lily/struct.go, network/surveyer.go, schedule/scheduler.go, schedule/scheduler_test.go
- closes #723
- adds a new test `Job Submit and wait`
- refactors the scheduler test, can add as a separate change if prefers.
=> feat(job): add job waiting option

tasks/msapprovals/msapprovals.go
=> fix: pass correct tipset to getTransactionIfApplied

go.mod, tasks/actorstate/market.go, tasks/actorstate/market_test.go
=> fix: sanitize illegal utf8 in market deal proposal labels

commands/daemon.go
=> Document --bootstrap flag in daemon command.

CHANGELOG.md
Fix the CHANGELOG to include instructions for fixing the data produced by previous releases.
=> chore(docs): Add instructions to fix v0.8.6 data bugs

tasks/actorstate/market/context.go, tasks/actorstate/market/context_test.go
=> fix: market_deal_proposal label field doesn't contain null characters

CHANGELOG.md
Will want to follow this with completing https://github.com/filecoin-project/lily/issues/966
=> docs: write v0.10.0 changelog

go.mod, go.sum
=> deps: update go-amt-ipld version

go.mod, go.sum
=> deps: update lotus and ffi versions

commands/setup.go, main.go
caused metrics to never register for redis
=> fix: create asynq inspector

chain/indexer/distributed/queue/tasks/gapfill.go, chain/indexer/distributed/queue/tasks/index.go, chain/indexer/distributed/queue/worker.go, lens/lily/impl.go
This PR allows the tipset worker to operate with all storage systems (Noop and CSV).
- closes #1029
=> feat: TipSetWorker accepts all storage systems

.circleci/config.yml
closes: #1046 
issue looks like glibc being incompatible with docker engine versions <= 20.10.9
=> fix: upgrade docker engine

chain/actors/builtin/miner/actor.go.template, chain/actors/builtin/miner/diff_v8.go, chain/actors/builtin/miner/miner.go, chain/actors/builtin/miner/state.go.template, chain/actors/builtin/miner/v0.go, chain/actors/builtin/miner/v2.go, chain/actors/builtin/miner/v3.go, chain/actors/builtin/miner/v4.go, chain/actors/builtin/miner/v5.go, chain/actors/builtin/miner/v6.go, chain/actors/builtin/miner/v7.go, chain/actors/builtin/miner/v8.go, chain/actors/builtin/miner/v9.go, chain/datasource/miner.go, chain/indexer/integrated/processor/state.go, main.go, model/actors/miner/precommitV9.go, schemas/v1/10_miner_precommit_v9.go, tasks/actorstate/actorstate.go, tasks/actorstate/miner/precommit.go, tasks/actorstate/miner/precommitv9.go, tasks/api.go
=> schema: implement precommitinfov9 schema and extractor

chain/indexer/integrated/processor/state.go, chain/indexer/tasktype/table_tasks.go, lens/util/repo.go, model/actors/miner/beneficiary.go, schemas/v1/11_miner_beneficiary.go, tasks/actorstate/miner/beneficaries.go
=> schema: implement minerbeneficiary task and schema

chain/actors/builtin/datacap/actor.go.template, chain/actors/builtin/datacap/datacap.go, chain/actors/builtin/datacap/diff.go, chain/actors/builtin/datacap/state.go.template, chain/actors/builtin/datacap/util.go, chain/actors/builtin/datacap/v9.go, chain/indexer/integrated/processor/state.go, chain/indexer/tasktype/table_tasks.go, lens/util/repo.go, model/actors/datacap/state.go, schemas/v1/12_datacap_balance.go, storage/sql.go, tasks/actorstate/datacap/balance.go
=> schema: implement datacap balance extractor and schema

tasks/messageexecutions/vm/task.go
- ya'll got it from here <3
- might fix #1088 try it and see
=> fix: don't parse VM messages whos parent failed to apply

.circleci/config.yml
- fix regex match for `cd/staging`
- ci match for `cd/staging` also builds calibnet docker
=> chore(ci): Build calibnet; fix cd/staging regex

commands/chain.go
| Version | Name | Family | Code |
| ---:| --- | --- | --- |
| 0 | fil/1/account | account | bafkqadlgnfwc6mjpmfrwg33vnz2a |
| 2 | fil/2/account | account | bafkqadlgnfwc6mrpmfrwg33vnz2a |
| 3 | fil/3/account | account | bafkqadlgnfwc6mzpmfrwg33vnz2a |
| 4 | fil/4/account | account | bafkqadlgnfwc6nbpmfrwg33vnz2a |
| 5 | fil/5/account | account | bafkqadlgnfwc6njpmfrwg33vnz2a |
| 6 | fil/6/account | account | bafkqadlgnfwc6nrpmfrwg33vnz2a |
| 7 | fil/7/account | account | bafkqadlgnfwc6nzpmfrwg33vnz2a |
| 8 | fil/8/account | account | bafk2bzacedudbf7fc5va57t3tmo63snmt3en4iaidv4vo3qlyacbxaa6hlx6y |
| 9 | fil/9/account | account | bafk2bzacect2p7urje3pylrrrjy3tngn6yaih4gtzauuatf2jllk3ksgfiw2y |
| Method Name | Method Number |
| --- | ---:|
| Constructor | 1 |
| PubkeyAddress | 2 |
| …
=> feat: update command to print all actor codes and version

Makefile, chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, chain/indexer/tasktype/table_tasks.go, chain/indexer/tasktype/tasks.go, chain/indexer/tasktype/tasks_test.go, model/messages/messageparams.go, schemas/v1/14_message_params.go, storage/sql.go, tasks/messages/messageparam/task.go
- create a table that records raw message parameters
=> feat: implement message param schema and task

chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go
ensure we process actor version 10 for appropriate actor tasks.
=> fix: process actor version 10 tasks

commands/chain.go, lens/lily/api.go, lens/lily/struct.go
Resolve the [issue](https://github.com/filecoin-project/lily/issues/1187)
=> feat: add new command: prune

tasks/fevm/blockheader/tasks.go, tasks/fevm/receipt/tasks.go, tasks/fevm/transaction/tasks.go
Align the height setting for every task.
=> fix: align the task height

commands/chain.go
=> fix: var names for chain commands

chain/datasource/datasource.go, model/fevm/transaction.go, schemas/v1/24_fevm_transaction.go, schemas/v1/31_add_message_and_address_and_actor_names_to_fevm_transcation.go, tasks/api.go, tasks/fevm/transaction/tasks.go
Add more fields in `fevm_transactions` for easier analysis, and introduce structs: `ActorInfo` and cache to expedite the retrieval of actor-related information.
=> feat: add more fields in fevm transaction

schemas/v1/35_add_pkey_for_tables.go
Add the default value for new column.
=> fix: hot fix migration script

go.mod, go.sum, storage/sql.go
=> fix: use exponential backoff to attempt reconnect to tsdb

go.mod, go.sum
Sync with latest lotus version.
=> chore: upgrade the lotus version to v1.26.3

chain/actors/builtin/market/actor.go.template, chain/actors/builtin/market/market.go, chain/actors/builtin/market/state.go.template, chain/actors/builtin/market/v0.go, chain/actors/builtin/market/v10.go, chain/actors/builtin/market/v11.go, chain/actors/builtin/market/v12.go, chain/actors/builtin/market/v13.go, chain/actors/builtin/market/v2.go, chain/actors/builtin/market/v3.go, chain/actors/builtin/market/v4.go, chain/actors/builtin/market/v5.go, chain/actors/builtin/market/v6.go, chain/actors/builtin/market/v7.go, chain/actors/builtin/market/v8.go, chain/actors/builtin/market/v9.go, tasks/actorstate/market/sector_deals_v2.go
Introduce the new method `GetProviderSectorsByDealID` and optimize the original `GetProviderSectors` method by minimizing the number of loops and altering the return value type.
=> feat: refine the provider sectors func

chain/datasource/datasource.go, lens/util/builtinactor.go, tasks/actorstate/actorstate.go, tasks/actorstate/miner/sector_events.go, tasks/actorstate/miner/sector_events_test.go, tasks/api.go, tasks/messages/builtinactorevent/task.go, tasks/test/api.go
Fix the issue: https://github.com/filecoin-project/lily/issues/1297
=> feat: refine the miner sector event by using builtin_actor_event function

go.mod, go.sum
Fix the bls version from lotus: https://github.com/filecoin-project/lotus/pull/12469/files
=> fix: downgrade the bls version to stable version

chain/actors/builtin/miner/utils.go, model/actordumps/miner_actor_dump.go, schemas/v1/42_add_fields_in_miner_dump.go, tasks/periodic_actor_dump/miner_actor/tasks.go
```
lily migrate --db="postgres://{user}:{password}@{host}:{port}/lily?sslmode=disable" --name migration --schema {schema} --to 1.42
```
=> feat: add new fields in miner actor dumps

go.mod, go.sum
refer: https://github.com/filecoin-project/lotus/releases/tag/v1.32.3
=> chore: update lotus

tasks/periodic_actor_dump/miner_actor/tasks.go
resolve: https://github.com/filecoin-project/lily/issues/1349
=> chore: clean the log in miner_actor_dump

lens/interface.go, lens/lily/impl.go
=> fix: replace eth.EthTransactionAPI with full.EthTransactionAPIV1
