filecoin-project/lily

main.go, model/actors/miner/sectordeals.go, model/actors/miner/state.go, model/actors/miner/task.go, model/genesis/task.go, run.go, services/processor/processor.go, services/processor/scheduler.go, services/processor/tasks/genesis/genesis.go, services/processor/tasks/interface.go, services/processor/tasks/miner/miner.go, storage/sql.go
only handles miner state, as more models are added the genesis task
processing logic will need to be extended to include new models in the
genesis state.
special handling is required here since *most* task processing works by
comparing the state of actors across two tipsets, since there isn't a
tipset before the genesis block we need special handling.
to follow #7
=> feat(genesis): Add task for processing genesis state

.circleci/config.yml
adds jobs for running tests and for building in docker. We can make this stricter by adding go vet and friends if wanted. The next step with this is to get the tests running with the docker compose config, but I want to land the simple version first.
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
=> chore: add circle ci

README.md, hooks/post_checkout
Our autobuilds on dockerhub are failing when it tries to fetch the submodule.
The internet suggests the fix is to use dockerhub hooks to init the submodule post checkout.
see: https://stackoverflow.com/questions/58690455/how-to-correctly-initialize-git-submodules-in-dockerfile-for-docker-cloud
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
=> chore: fix docker hub submodule error

lens/lotus/api.go, lens/lotus/cachestore.go, lens/lotus/lotus.go, run.go, services/indexer/indexer.go, services/indexer/indexer_test.go, services/indexer/types.go, services/processor/processor.go, services/processor/scheduler.go, storage/sql_test.go
Move goroutine management out of processor start into the caller so we can return an
error instead of panicing. Also make NewCacheCtxStore return an error instead of
panicing.
Add informative context to errors throughout core logic of indexer, processor and storage.
=> chore: tighten up error propagation

.circleci/config.yml, hooks/post_checkout, scripts/push-docker-tags.sh
Adds script and ci config to push to docker hub when.
- the master or main branch changes
- semver like tags are pushed to the repo
Pushing a semver like tag pushes a docker image with the same tag. The docker latest tag points to the last semver version tag
Pushing changes to main or master gets you a docker tag of the form <branch name>-<date>-<truncated commit sha>
e.g main-2020-f435621. a <branch>-latest docker tag is provided as a convenince if you really want the bleeding edge. The branch name is included in the docker tag name to make that clearer.
This is a tweak on what I set up for go-ipfs in https://github.com/ipfs/go-ipfs/pull/6949
This PR is motivated by the fact that dockerhub has repeatedly been a time sink, and it's latest issue is that our docker builds fail there when we …
=> chore: push docker tags from ci

main.go, run.go
Proposed for discussion
BREAKING CHANGE: this changes the cli interface to remove the run subcommand.
Previously the indexer and procerror would be started via:
sentinel-visor run indexer
sentinel-visor run processor
After this change:
sentinel-visor index
sentinel-visor process
=> feat: remove run subcommand and make index and process top level

main.go, run.go, services/processor/processor.go, services/processor/tasks/common/actor.go, services/processor/tasks/genesis/genesis.go, services/processor/tasks/init/init_actor.go, services/processor/tasks/market/market.go, services/processor/tasks/message/message.go, services/processor/tasks/miner/miner.go, services/processor/tasks/power/power.go, services/processor/tasks/reward/reward.go
Removes hard coded log levels so the log-level flag now properly controls the default log level.
Adds a log-level-named flag which takes a comma delimited list of logger:level pairs that specify the log levels for specific loggers. Can also be set via the VISOR_LOG_LEVEL_NAMED environment variable.
Fixes #32
=> feat: respect log level flag and allow per logger levels

services/indexer/indexer_test.go, storage/sql.go, storage/sql_test.go, testutil/db.go
Helps avoid accidental wiping of data in local database.
=> feat: add VISOR_TEST_DB environment variable to specify test database

Dockerfile
sentinel-visor binary was recently renamed to visor, which breaks existing docker image.
adjust entrypoint accordingly
=> change binary name in entrypoint

storage/migrations/2_visor_initial.go
The issue I hit that required this fix is that with a brand new database running the following fails:
```
$ env LOTUS_DB='postgres://postgres:password@127.0.0.1:5432/postgres?sslmode=disable' ./visor --allow-schema-migration index 15:45
2020-10-01T15:46:15.848+1000	INFO	visor/lens/lotus	lotus/lotus.go:54	Lotus API version: 0.8.0+git.2c1d96bca
2020-10-01T15:46:15.853+1000	INFO	visor	commands/setup.go:58	connect database: database schema is too old and requires migration
2020-10-01T15:46:15.853+1000	INFO	visor	commands/setup.go:61	Migrating schema to latest version
2020-10-01T15:46:15.857+1000	INFO	storage	storage/migrate.go:68	current database schema is version 0
2020-10-01T15:46:15.857+1000	INFO	storage	storage/migrate.go:88	running schema migration from version 0 to version 3 …
```
=> convert json to jsonb actor_states table

storage/migrations/1_chainwatch.go
These statements were causing
```
2020-10-04T03:00:06.280Z	FATAL	visor	sentinel-visor/main.go:102	migrate schema: run migration: ERROR #42501 must be member of role "postgres"
```
=> fix(migration): Remove set ownership

commands/run.go, commands/setup.go, lens/interface.go, lens/lotus/api.go, model/derived/gasoutputs.go, model/messages/task.go, model/visor/processing.go, storage/migrations/6_tipset_processing_tables.go, storage/sql.go, storage/sql_test.go, tasks/actorstate/actorstatechange.go, tasks/indexer/blockdata.go, tasks/indexer/chainheadindexer_test.go, tasks/indexer/chainhistoryindexer.go, tasks/indexer/chainhistoryindexer_test.go, tasks/message/gasoutputs.go, tasks/message/message.go
This change adds a gas outputs processing task. The results of the task are written to
a new table derived_gas_outputs. The task fetches batches of messages that have receipts
and calls the lotus vm ComputeGasOutputs method, persisting the results.
This change also performs a significant refactor of the visor processing tables. Previously
the chain indexers would write duplicate rows to visor_processing_statechanges and
visor_processing_messages. Each of those tables contained claimed_until, completed_at and
errors_detected columns. They were used by the ActorStateChange and Message tasks. However
if we were to add another task that processed tipsets we would need to add another processing
table and then reindex the entire chain to populate it.
To avoid this, the …
=> feat: compute gas outputs

tasks/actorstate/actorstate.go, tasks/actorstate/actorstatechange.go, tasks/message/gasoutputs.go, tasks/message/message.go
This change alters tasks to avoid setting a context deadline when no work has been
leased.
=> fix: use context deadlines only if task has been assigned work

tasks/indexer/chainhistoryindexer.go, tasks/indexer/chainhistoryindexer_test.go
Commit 3b98708 broke the chain indexer test after a reorganization of the chain
walking logic. It stopped processing when reaching genesis but omitted to
persist the genesis block infomation. This change fixes the bug.
=> fix: chain history indexer includes genesis

commands/setup.go, go.mod, lens/interface.go, lens/lotus/lotus.go, lens/lotusrepo/repo.go, main.go
Create a full lotus.Node (without bringing it `Online`) and use its chainstore / api for a lens as an alternative to the jsonrpc API.
address #68
=> in-process lotus "repo" lens

go.mod, go.sum, tasks/actorstate/actor.go, tasks/actorstate/actorstate.go, tasks/actorstate/actorstate_test.go, tasks/actorstate/genesis_test.go, tasks/actorstate/init.go, tasks/actorstate/market.go, tasks/actorstate/market_test.go, tasks/actorstate/miner.go, tasks/actorstate/power.go, tasks/actorstate/reward.go, testutil/ipfs.go
The first commit adds a test for market actor state diffing and adds a mock API that will help with writing future unit tests for actor state extraction.
The second commit changes the implementation of market state extraction to combine the deal and proposal diffing into a single predicate so the old and new actor states are only loaded once.
=> perf: minor optimization of market actor diffing

commands/run.go, commands/setup.go, go.mod, go.sum, storage/migrations/7_chainvis_views.go, tasks/views/chainvis.go
This PR serves two purposes:
1. It is a proposal for supporting optional views within Visor. The idea here is that certain views are not always worth maintaining during normal processing. Within, we define a pattern for a materialized view which can be instantiated without data and optionally refreshed by passing in `--chainvis-refresh-rate=1m` with some value greater than 0 (which disables the refresh loop entirely).
2. It is a proposal to support chain visualization views for queries associated with https://github.com/DigitalMOB2/filecoin-lotus-explorer-playground/. This view is a contract for data we promise to support for this external dependency. This will be a UI dependency which sits alongside Grafana as one of out first custom visualizations on top of Sentinel.
Overall, this …
=> feat(task): Create chainvis views and refresher

commands/debug.go, main.go, storage/sql.go, tasks/actorstate/actorstate.go
Usage: `./visor debug --actor-head <head-cid>`
```
$ ./visor --log-level=debug debug --actor-head bafy2bzaceav5xqjxizyht2o7ps5zt6zsky6itsvo5hzgwbsgehrrw6zhvrw6m
2020-10-10T22:37:15.637Z        INFO    visor/lens/lotus        lotus/lotus.go:53       Lotus API version: 0.9.0+git.8f35a5c0
SELECT "processing_actor"."head", "processing_actor"."code", "processing_actor"."nonce", "processing_actor"."balance", "processing_actor"."address", "processing_actor"."parent_state_root", "processing_actor"."tip_set", "processing_actor"."parent_tip_set", "processing_acto
r"."height", "processing_actor"."added_at", "processing_actor"."claimed_until", "processing_actor"."completed_at", "processing_actor"."errors_detected" FROM "visor_processing_actors" AS "processing_actor" WHERE (head = …
```
=> feat(debug): Process actor by head without persistance

storage/migrate.go, storage/sql_test.go
=> fix: verify there are no missing migrations before migrating

.gitignore, commands/run.go, commands/setup.go, model/visor/stats.go, storage/migrations/9_processing_stats.go, storage/sql.go, tasks/stats/processing.go
Add a task that writes summary stats to a new table visor_processing_stats.
For each tipset processor (message discovery, state change, chain economics) and
for each message processor (currently only gas outputs) and for each actor state
change it writes the following metrics:
- total number of items that have been discovered for processing
- total number of items that have been processed
- total number of items that have been processed but reported an error
- total number of items that are currently being processed
- highest epoch that has been processed
- highest epoch that has not been processed
Stats are written every minute and only a single global task is used.
Note: branched from #94
=> feat: add visor processing stats table

storage/sql.go
Makes is easier to identify visor in postgres system tables such as `pg_stat_activity`
=> feat: set application name in postgres connection

commands/run.go, tasks/indexer/chainhistoryindexer.go
Makes batch size configurable. The high batch size was causing enormous insert queries
to be sent to postgres which were always taking > 10s to process, holding locks in the
process.
=> perf(db): reduce batch size for chain history indexer

model/messages/gaseconomy.go, model/messages/task.go, storage/migrations/0_null.go, storage/migrations/10_message_gas_economy.go, storage/migrations/8_message_gas_economy.go, storage/sql.go, tasks/message/message.go
- Implement Message Gas Economy model for tracking Chain Capacity Usage and Base fee.
- Fix what I believe to be a bug in the migration logic by including a null migration at version 0 (I _think_ this might relate to #89 but am not sure).
=> Base fee and chain capacity tracking.

storage/migrations/10_message_gas_economy.go
I don't think we have deployed a version of visor beyond this, given that I feel comfortable modifying the migration. If there are strong feelings against this I will modify it by adding another migration instead of altering this one.
=> fix(migration): message gas economy uses bigint

build/grafana/provisioning/dashboards/dashboard-visor-processing.json
Add a dashboard to track processing completion using the visor_processing_stats table
=> feat: add dashboard for process completion

model/visor/stats.go, storage/migrations/9_processing_stats.go, tasks/stats/processing.go
The processing indexes are very slow to create against populated databases. Remove them
and add them back in as part of a later conversion of the processing tables to
hypertables (see https://github.com/filecoin-project/sentinel-visor/pull/111)
While we are amending this migration, also change the structure of the visor_processing_stats
table. Fixes https://github.com/filecoin-project/sentinel-visor/issues/120
=> fix(schema): remove blocking processing indexes and improve processing stats table

commands/run.go, schedule/scheduler.go
Sets the defaults for tasks to "off". The expectation should be that new tasks added won't unexpectedly start on existing deployments when Visor is upgraded.
=> feat: set default numbers of workers to zero in run subcommand

docker-compose.yml, model/actors/common/actors.go, model/actors/market/dealproposal.go, model/actors/market/dealstate.go, model/actors/miner/power.go, model/actors/miner/precommit.go, model/actors/miner/sector.go, model/actors/miner/sector_events.go, model/actors/miner/sectordeals.go, model/actors/miner/sectorposts.go, model/actors/miner/state.go, model/actors/power/chainpower.go, model/actors/reward/chainreward.go, model/blocks/header.go, model/blocks/parent.go, model/messages/blockmessage.go, model/messages/gaseconomy.go, model/messages/message.go, model/messages/parsedmessage.go, model/messages/receipt.go, storage/migrations/14_height_partitoning.go, storage/sql.go, storage/sql_test.go, tasks/actorstate/actor.go, tasks/actorstate/genesis.go, tasks/actorstate/market.go, tasks/actorstate/miner.go, tasks/actorstate/reward.go, tasks/message/message.go
This is a major rework of the database schema and may only be applied
to an empty database. It is not reversible without dropping the schema
and restating.
This change adds a height column to processing, message and actor
tables as part of the primary key and uses it
to partition the table as a timescale hypertable. Rough calculations of
expected number of rows per epoch and row widths are included to estimate
the potential chunk sizes of each hypertable. Timescale recommend that chunks
are small enough that the most recent can fit into 25% of main memory, summed
over all tables.
Additionally the indexes on the visor_processing tables have been analysed to
give the best performance for the work selection queries used by visor. The
tipsets and message processing table indexes fully cover …
=> feat: convert processing, block and message tables to hypertables

go.mod, go.sum, tasks/message/message.go
* use a child tipset when available to learn type of destination actor for message parsing
=> Limit cases where message parsing fails

.circleci/config.yml, .gitmodules, Makefile, go.mod, go.sum, tasks/message/message.go
visor shouldn't be actually shelling out to ffi code to create or verify proofs.
As such, it's easier to use native golang stubs of the ffi methods, rather than needing to build the rust binary and play the cgo dance.
simplifies the path for #164
=> Replace filecoin-ffi with stubs to simplify build process

commands/debug.go, commands/run.go, commands/setup.go, go.mod, go.sum, lens/carrepo/carrepo.go, lens/interface.go, lens/lotus/cachestore.go, lens/lotus/lotus.go, lens/lotusrepo/repo.go, lens/sqlrepo/repo.go, tasks/actorstate/actorstate.go, tasks/actorstate/actorstatechange.go, tasks/actorstate/genesis_test.go, tasks/chain/economics.go, tasks/indexer/chainheadindexer.go, tasks/indexer/chainheadindexer_test.go, tasks/indexer/chainhistoryindexer.go, tasks/indexer/chainhistoryindexer_test.go, tasks/message/gasoutputs.go, tasks/message/message.go, testutil/db.go, testutil/lens.go
Tasks are now passed an APIOpener which they use to acquire a lens. On
encountering a fatal error the task exits and closes the lens. The scheduler
restarts the task after a delay allowing the task to attempt a new connection
to the lens.
The lotus lens opener returns a new rpc connection. The lotusrepo and carrepo
openers return a shared instance of their repo since they hold exclusive locks
over the store.
Fixes #98
=> feat: rpc reconnection on failure

commands/debug.go, commands/run.go, storage/sql.go, tasks/actorstate/actorstate.go
Leasing of actor states to process causes high contention on the visor_processing_actors
table since many instances are competing to lock rows to update their leases.
With this change, when --actorchange-lease is set to zero then the actor change processor
will not use leasing at all. Instead it assumes that it can work on any actor states
between the height ranges specified with --from and --to. It further subdivides that
height range by the number of workers started so each worker gets its own range of
heights to process.
Note that this requires manual coordination of height ranges allocated to each
instance of visor otherwise each instance may duplicate work performed by another
instance.
Note also that --to should be set to a reasonable value, typically under the current
height of the …
=> feat: allow actor state processor to run without leasing

storage/sql.go
Includes the change made in https://github.com/filecoin-project/sentinel-visor/compare/mg/optimize-lease
Improves actor leasing query timings over 10x (from mean 237153.5ms to 19579.7ms) see https://github.com/filecoin-project/sentinel-visor/issues/188
=> perf: include height restrictions in update clauses of leasing queries

model/derived/gasoutputs.go, storage/sql.go, storage/sql_test.go, tasks/actorstate/actorstate.go, tasks/message/gasoutputs.go
Helps with https://github.com/filecoin-project/sentinel-visor/issues/188 and https://github.com/filecoin-project/sentinel-visor/issues/183
Avoids the update needing to traverse all hypertables when looking for the item to update.
=> perf: ensure processing updates always include height in criteria

.circleci/config.yml
Update CI to:
- no longer build docker images on all commits to master or branches
- include RC tags in docker builds/pushes
=> chore: Include RC releases in push docker images

go.mod, go.sum, model/actors/power/claimedpower.go, model/actors/power/task.go, model/genesis/task.go, storage/migrations/16_power_actor_claims.go, tasks/actorstate/actorstate_test.go, tasks/actorstate/genesis.go, tasks/actorstate/genesis_test.go, tasks/actorstate/miner.go, tasks/actorstate/power.go, tasks/actorstate/power_test.go
This PR does the following:
- adds a `power_actor_claims` table to track claimed power by all miners in the power actor's state.
- updates `power_test.go` and mock api to work with power actor changes.
- shares power actor extractor logic with genesis task
closes #171
~blocked on https://github.com/filecoin-project/lotus/pull/4628~
=> feat: add power actor claim extraction

tasks/message/message.go
this is a bit unfortunate because for some binary fields this could lead to corruption, but we probably won't be dealing with those fields meaningfully in this table.
=> remove null bytes from message params

Makefile
I'd like to avoid fetching `git-chnglg` when I run make (also the `-u` in the `go get` was cauing go modules to be updated on calls to `make`). Instead `make changelog` runs the binary using:
```
go run go run github.com/git-chglog/git-chglog/cmd/git-chglog ...
```
=> fix: don't update go modules when running make

storage/sql.go
This change sets the application name to the current version only if a name has not already been specified. This allows us to assign names to instances by including `application_name=foo` as part of the the postgres connection url, e.g. `postgres://user:password@server/database?application_name=headindexer'
The application name is shown in the `pg_stat_activity` table.
=> feat: allow application name to be passed in postgres connection url

lens/lotusrepo/repo.go, main.go
Extracted from iand/beefy
Sometimes we need to open the lotus repo as writeable when using the lotusrepo lens. This adds a new `repo-read-only` flag that defaults to true. Set to false to open a writeable repo.
=> feat: add repo-read-only flag to enable read or write on lotus repo

storage/migrations/18_msig_transactions.go, storage/migrations/19_remove_unused_tables.go
Just want to be explicit about the changes I'm making to make latest hotfix migrations agree with what is already deployed to `master`.
NOTE: This will FBUAR anyone's visor database who has already migrated up to v17.
=> Reorder migrations after merging latest master

tasks/actorstate/power.go
Extractions were working but stored with height 0
Closes #224
=> fix: include height with chain power results

storage/migrations/19_height_functions.go, storage/migrations/21_height_functions.go
adds `unix_to_height` and `height_and_unix` to translate a unix epoch in seconds to a fil epoch. Makes searching the messages tables more fun.
This is mainnet specific, so this may not be the right approach. I'd need to be able to programmatically set the initial unix epoch time to suport other networks.
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
=> feat: functions to convert unix epoch to fil epoch

commands/debug.go, commands/run.go, commands/setup.go, model/actors/common/actors.go, model/actors/miner/sectorevents.go, model/actors/miner/task.go, model/actors/power/chainpower.go, model/interface.go, tasks/message/message.go
The purpose of this rather superficial changes is to better support custom, ad-hoc tooling that re-uses logic present in sentinel-visor.
=> Export some helpers and add some types

tasks/actorstate/actorstate_test.go, tasks/actorstate/init_test.go, tasks/actorstate/market_test.go, tasks/actorstate/multisig_test.go, tasks/actorstate/power_test.go, tasks/actorstate/reward_test.go
- remove returned errors from mock api helper methods
- condense tipset creation and storeage of tipset in mock api
- rename methods to reflect their action -- `must` will do the thing or fail the test.
=> polish(mockapi): accepts testing.TB and produces less errors

storage/sql_test.go, tasks/actorstate/genesis_test.go, tasks/indexer/chainheadindexer_test.go, tasks/indexer/chainhistoryindexer_test.go, testutil/db.go
A recent refactoring wrapped the deferred database cleanups in an error assertion but defer evaluates arguments at the call site so this was invoking the cleanup function immediately.
=> fix: tests defer database cleanup without invoking

tasks/actorstate/genesis_test.go, tasks/indexer/chainheadindexer_test.go
* `miner_states` => `miner_infos` as advised by comment in migration 19
* `miner_powers` => `power_actor_claims` as advised by comment in migration 19
* `drand_entries` removed in migration 20
=> fix: truncated tables in tests

model/nodata.go, tasks/actorstate/account.go, tasks/actorstate/account_test.go, tasks/actorstate/actorstate.go
~~This PR enables Sentinel to persist state for the burnt funds actor without having to extract and persist data for ALL accounts.~~
~~It registers an `AccountExtractor` for the Account Actor CID and introduces the concept of a `FilteredExtractor`. If an extractor is a `FilteredExtractor` then `processActor` will call it's `Filter` method to see if it wants to extract data for a given actor.~~
~~At the moment the `AccountExtractor` is only interested in the burnt funds account and has no specialized extraction needs beyond what is automatically extracted by the common extractor. It means it's `Extract` method is basically a noop.~~
This PR adds an account actor extractor so that basic state is extracted for account actors.
=> feat: extract basic account actor states

main.go
Change the default parameter sentinel-visor to visor in the command line
jaeger-service-name, because the compiled binary is visor by default.
=> refactor(cmd): Modify command line default parameters

storage/migrations/22_height_functions_fast.go, storage/migrations/24_height_functions_fast.go
add attributes to the height functions to allow postgres to optimise them
- IMMUTABLE - the function cannot modify the database and always returns the same result when given the same argument value
- RETURNS NULL ON NULL INPUT - the function is not executed when there are null arguments; instead a null result is assumed automatically.
- PARALLEL SAFE - safe to run in parallel mode without restriction.
with these in place my test query execution time goes down from 3m40s to 12s, which is as fast as the inlined, functionless version.
see: https://www.postgresql.org/docs/12/sql-createfunction.html
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
=> fix: optimisable height functions

storage/migrations/23_miner_sector_deals_pk.go
This retrospectively changes migration 23 but keeps backwards compatibility. Changing the primary key on a hypertable can't be done while it contains data. Since the data in miner_sector_deals is incomplete and we need to backfill then we can truncate the table. 
This change introduces a pattern we can use to only perform destructive data changes when needed. We wrap the migration in a check for the existence of the new constraint.
=> fix(migration): don't recreate miner_sector_deals primary key if it is correct

storage/migrate.go, storage/migrations/1_chainwatch.go
Instead, run this statement before obtaining the global lock for migrations.
Fixes #179 .
=> fix(migrations): CREATE EXTENSION deadlocks inside migrations global lock

chain/actor.go, chain/indexer.go, commands/walk.go, commands/watch.go
This replaces the `actorstates` and `actorstatesparsed` tasks with per-actor tasks which allows us to run visor with selected actors being fully extracted. They are implemented as separate tasks rather than a parameterised version of `actorstates` so that the outcome of each task can be tracked in the `visor_processing_reports` table. This allows users to quickly determine whether actor extraction has been performed for any given epoch.
=> feat: allow finer-grained actor task processing

lens/interface.go, tasks/actorstate/actorstate.go
There has been some discussion of embedding visor into a lotus daemon. Reducing the API required by visor aims to decrease friction of making that change.
=> chore(api): trim the lens API to required methods

commands/migrate.go, commands/setup.go, go.mod, go.sum, main.go, storage/sql.go, storage/sql_test.go
=> Allow model upsertion

model/actors/market/dealproposal.go, model/actors/market/dealstate.go, tasks/actorstate/market.go
I had these changes laying around. The market actor model was still looping every element on the slice when doing a batched-persist, which is very slow. That said, the whole market-actor processing does NOT get sped-up too much by this.
Additionally, export some extractor methods for the market actor, as that allowed me playing with a custom extractor, even though it was still too slow.
=> Market actor: Export some methods and improve batching

.circleci/config.yml
Fixes https://github.com/filecoin-project/sentinel-visor/issues/339
=> fix(ci): Pin TimescaleDB to v1.7 on Postgres v12

lens/interface.go, tasks/actorstate/actorstate.go, tasks/actorstate/actorstate_test.go, tasks/actorstate/miner.go
- closes #342
Due to the complexity of the miner actor state there there is no test coverage for this change, manual verification is required.
Manual validation was performed by running:
```
./visor --log-level=debug --db="postgres://postgres:password@localhost:5432/postgres?sslmode=disable" --lens="lotusrepo" --repo="~/.lotus" --repo-read-only=false walk --from 10000 --to 11000 --tasks=actorstatesminer
``` 
A CSV of the `miner_sector_posts` table after running the above command can be seen here: https://ipfs.io/ipfs/QmV4RbVzgtD5Nc9ujpMRqyuAsjBSzELSqo7eWY4RP7Hn26
When the aformentioned command was ran against master the `miner_sector_posts` table was empty.
=> fix(miner): extract miner PoSt's from parent messages

README.md, docker-compose.yml
=> docs: Update README and docker-compose to require use of TimescaleDB v1.7

model/actors/miner/feedebt.go, model/actors/miner/lockedfunds.go, model/actors/miner/precommit.go, model/actors/miner/sector.go, model/actors/power/chainpower.go, model/actors/power/claimedpower.go, model/actors/reward/chainreward.go, model/derived/gasoutputs.go, model/messages/gaseconomy.go, model/messages/message.go, storage/migrations/26_use_numberic_types.go, storage/migrations/27_use_numberic_types.go
together with https://github.com/filecoin-project/sentinel-visor/pull/301 closes #244. will need a rebase if #301 goes in first.
=> chore(sql): user numeric type to represent numbers

commands/setup.go
Metrics show that we are continually fetching ~20k blocks per tipset which suggests that the LRU cache used is too small. Increasing it to 500k made a big difference in performance as shown in grafana screenshot below. This change bumps the LRU to 50k to balance memory consumption with performance.
Top-right: note number of requests being made to API drop off dramatically with a larger LRU
Mid-right: note processing times are lower
Bottom-left: memory consumption is up, but not greatly so
The spikes appear to be unrelated and are not present once visor has been running for a while.
=> chore: increase lens object cache size

storage/migrations/9_processing_stats.go
Created a new database for calibnet analysis and unfortunately it defaults to v2.0.1 of the timescale extension and there is no way to downgrade it. This function has been renamed in v2 so our migration fails. Since this table is no longer used it was simplest to remove the function from the migration.
=> schema: remove use of add_drop_chunks_policy timescale function

lens/util/repo.go
Ensure the chain store is set on LensAPI to avoid a null pointer when StateGetActor is called.
=> fix(repo-util): set chainstore on repo lens util

chain/indexer.go, chain/message.go, lens/lotus/api.go, lens/util/repo.go, model/msapprovals/msapprovals.go, storage/migrations/28_multisig_approvals.go, storage/sql.go, tasks/actorstate/multisig.go, tasks/messages/message.go, tasks/msapprovals/msapprovals.go
Create and populate a new `multisig_approvals` table containing multisig transaction approvals derived from propose and approve messages sent to the multisig actor. Create a new task called `msapprovals` to run the extraction. 
Refactored the message task and moved it under the tasks package and then created a msapprovals package as a sibling. Ideally I would like to see all the named tasks move in this way so the chain package just contains chain walking/watching logic.
Anecdotally the `msapprovals`  task takes a few seconds to run per tipset, depending on the number of multisig messages.
(apologies for the dozens of hacky commits which I needed for shipping code for intractive testing - will squash them anyway before merge) 
Fixes #388
=> feat: record multisig approvals

.circleci/config.yml, scripts/push-docker-tags.sh
Minor adjustments:
- increase default SHA length to 8 chars
- include truncated SHA as part of tag name for all `master` docker images
- cleanup unused behavior in docker build script
The name adjustments are to support automated deployments of `master` branch with versioned tags.
=> chore: make default docker image name deterministic

tasks/actorstate/multisig.go, tasks/msapprovals/msapprovals.go
=> fix: msapprovals missing pending transaction

.circleci/config.yml, scripts/push-docker-tags.sh
This PR includes fixes to further support the automatic deployment pipeline work. Specifically:
- Simplify docker build pipeline and scripts (remove GIT_BRANCH case; isolate workflow commands)
- Fix docker image name (remove extraneous `-dev` on image name)
- Restore semver publishing behavior (trigger was removed in prior PR)
- Fix semver dev image labeled as production
- Fix step names to be understandable in CircleCI UI
Proof of work:
These images were actually pushed to docker hub if you'd like to test them out:
Dev builds have `bin/bash` shell for entrypoint: `docker run -it --rm --entrypoint=/bin/bash filecoin/sentinel-visor:v0.0.0-rc0-dev`
Prod builds have `bin/sh` shell for entrypoint: `docker run -it --rm --entrypoint=/bin/sh filecoin/sentinel-visor:v0.0.0-rc0`
- Example build …
=> fix(docker): restore semver build; correct names; simplify build pipeline

chain/indexer.go, tasks/actorstate/task.go, tasks/blocks/task.go, tasks/chaineconomics/economics.go, tasks/chaineconomics/economics_test.go, tasks/chaineconomics/task.go
Moved all the task-processing code out of chain package and into packages under tasks. Renamed some to align with the names of tasks passed on the command line so they are easier for people to locate. Renamed XYZProcessor to Task where needed. No functional changes.
=> chore: move task implementations out of chain package

chain/indexer.go, tasks/actorstate/task.go, tasks/chaineconomics/task.go, tasks/messages/message.go, tasks/msapprovals/msapprovals.go
Following investigation by @placer14 we suspect the panic in #411 is due to concurrent modifications of the node field in the actor state task. When originally written this code was sequential but recent changes have introduced concurrent accesses to the field, namely when the Close method is called. I speculate this can happen when another task fails while an actor state task is still spawning goroutines. The task failure is detected by the indexer which closes all lenses used by the other running tasks, setting the node field to nil which is then passed to a new goroutine by the still-running task.  
This change guards accesses to the node field with mutexes in each of the tasks. The actor state task checks whether the api lens is available before processing and if it isn't returns a …
=> fix: guard concurrent accesses to node api

lens/util/store.go, vector/README.md, vector/runner.go, vector/vector_test.go
Baseline run
```
17:11 $ go test -v ./vector -run ^$ -bench=.* -benchtime=1m -timeout=30m
goos: linux
goarch: amd64
pkg: github.com/filecoin-project/sentinel-visor/vector
cpu: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
BenchmarkExecuteVectors
BenchmarkExecuteVectors/market_actor_models_495000_to_495010
BenchmarkExecuteVectors/market_actor_models_495000_to_495010-8         	       3	21806920691 ns/op	   1582196 gets/op	12998351082 B/op	275225185 allocs/op
BenchmarkExecuteVectors/power_actor_modesl_from_495000_to_595010
BenchmarkExecuteVectors/power_actor_modesl_from_495000_to_595010-8     	       9	7077350736 ns/op	     65863 gets/op	5241351523 B/op	91972824 allocs/op
BenchmarkExecuteVectors/chain_economics_models_from_epoch_512980_to_5129990 …
```
=> feat: add benchmarking of vectors

chain/tipset.go, chain/walker.go, chain/watcher.go, vector/runner.go
This change ensures the Run method on walker and watcher will only return once all persistence operations have been completed.
=> close TipSetObs in walker and watcher

commands/walk.go, vector/builder.go
- else subsequent calls to close will hang forever and jobs will never exit, e.g. walk will never exit without this change. Thanks @thattommyhall for reporting.
- fixes logic introduced in 8c6f0eed480c31218cd9de990b21f38127b65a1d
=> fix(indexer): only close TIpSetIndexer in walk and watch

.circleci/config.yml, lens/lily/impl.go
Linter error attempting to fix:
```
WARN [runner] Can't run linter goanalysis_metalinter: deadcode: analysis skipped: errors in package: [/home/circleci/project/lens/interface.go:14:2: could not import github.com/filecoin-project/lotus/chain/vm (/go/pkg/mod/github.com/filecoin-project/lotus@v1.5.1-0.20210304004200-f7ad0c6a2fac/chain/vm/syscalls.go:26:2: could not import github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper (/go/pkg/mod/github.com/filecoin-project/lotus@v1.5.1-0.20210304004200-f7ad0c6a2fac/extern/sector-storage/ffiwrapper/sealer_cgo.go:17:6: could not import github.com/filecoin-project/filecoin-ffi (/home/circleci/project/extern/filecoin-ffi/distributed.go:6:2: could not import github.com/filecoin-project/filecoin-ffi/generated …
```
=> fix(linter): make deps before linting in CI

commands/config.go, commands/daemon.go, commands/walk.go, commands/watch.go, config/config.go, go.mod, go.sum, lens/lily/api.go, lens/lily/impl.go, lens/lily/modules/events.go, storage/catalog.go, storage/sql.go
This adds a config file to the visor daemon which contains a section for database settings. The name of the storage can then be used when starting a walk or watch job: `visor watch --storage=MyCSV`
The config is shared with the embedded parts of lotus that we use.
Two types of storage are supported: postgresql and file. Multiple instances of each storage type can be specified:
```
[Storage]
[Storage.Postgresql]
[Storage.Postgresql.Database1]
URL = "postgres://postgres:password@localhost:5432/postgres"
PoolSize = 20
AllowUpsert = false
[Storage.Postgresql.Database2]
URL = "postgres://postgres:password@localhost:5432/sentinel"
PoolSize = 10
AllowUpsert = false
[Storage.File]
[Storage.File.MyCSV]
Format = "CSV"
Path = "/tmp"
```
This config is not read for the single-use `walk` and `watch` …
=> feat: add storage configuration to daemon

chain/indexer.go, commands/watch.go, tasks/actorstate/task.go
This fixes a hang that can occur when the tipset indexer is exited and restarted (such as when the api is unavailable). When this happened `t.persistSlot` would be filled with a token which caused the restarted indexer to assume there was a persistence goroutine running and wait forever. Fix this by probing the channel and then ensuring the probe token is removed.
Separately fix a bug that was preventing actor task errors from being persisted properly. They were being appended incorrectly to the slice.
=> fix: ensure persistence semaphore channel is drained on close

Dockerfile, Makefile, commands/migrate.go, commands/run.go, commands/setup.go, commands/util.go, commands/walk.go, commands/watch.go, lens/carrepo/carrepo.go, lens/lotus/lotus.go, lens/lotusrepo/repo.go, lens/s3repo/repo.go, lens/sqlrepo/repo.go, lens/vector/repo.go, main.go
Builds on #445 to better segregate flags so they only appear on relevant commands. 
The `visor run walk` and `visor run watch` commands now expect their database and lens flags to be specified after the subcommand, instead of after the visor command. This means that where previously we would use:
```
visor --db=foo --lens=lotus walk --from=1000 --to=1001
```
we will now use:
```
visor run walk --db=foo --lens=lotus --from=1000 --to=1001
```
The `migrate` command now also expects flags to be specified after the command.
Some consistency related changes:
- the `--api` flag has been renamed to `--lens-lotus-api` since it is used by the lotus lens to specify the api that visor will connect to. This reduces confusion from the daemon-oriented `--api` flag which specifies the api address of …
=> feat: clean up command line flags for single-run jobs

commands/watch.go
- we only need 1 window flag, else cli library panics
=> fix(cli): remove redundant window flags from watch

Dockerfile, Dockerfile.dev, Makefile
Noticed CI was broken on master. This has a few improvements.
Fixes:
- fix dev docker build to include hwloc dep ([example](https://app.circleci.com/pipelines/github/filecoin-project/sentinel-visor/1728/workflows/91dba3b9-42a5-40fc-9ad9-6a564c15d5bc/jobs/3798))
- remove vector data from `make dep` target (and from docker images) and add vector data artifacts to `make clean`. Vector data now available as `make vector-setup`.
- remove `||` on `make testfull` hack
=> fix: docker builds to include hwloc dep

tasks/actorstate/actor.go, tasks/actorstate/actor_test.go, tasks/actorstate/actorstate.go, tasks/actorstate/actorstate_test.go, tasks/actorstate/genesis.go, tasks/actorstate/init.go, tasks/actorstate/init_test.go, tasks/actorstate/market.go, tasks/actorstate/market_test.go, tasks/actorstate/miner.go, tasks/actorstate/multisig.go, tasks/actorstate/multisig_test.go, tasks/actorstate/power.go, tasks/actorstate/power_test.go, tasks/actorstate/reward.go, tasks/actorstate/reward_test.go, tasks/actorstate/task.go
Minor performance optimization.
When extracting actor states we already have the full tipset and its parent available so we can avoid calling the chain store to look up the tipset from its key. All the Lotus APIs do this too so we could further optimize by implementing alternate calls that accept a full tipset - I noted some of these in the ActorStateAPI interface.
Also remove calls to StateGetActor (which did an additional load of the tipset from its key) since the actor info is already passed to each extractor.
This allows us to shrink the ActorStateAPI interface by removing the ChainGetTipSet method. I also removed the ChainHasObj and ChainReadObj methods which were unused.
=> perf: remove redundant tipset lookups

.circleci/config.yml, .gitignore
Vector downloading was moved to its own make command (previously under `make deps` but removed because we don't want vectors in our docker containers). We need to ensure this command is run before tests in CI.
=> fix(ci): download vectors before running tests in CI

commands/lily.go, go.mod, go.sum, lens/lily/impl.go, lens/lily/struct.go, lens/lotus/api.go, lens/lotus/cachestore.go, lens/lotus/lotus.go, lens/lotusrepo/repo.go, lens/util/repo.go, lens/vector/repo.go, testutil/lens.go
Imports a commit past the v1.8.0 tag to get access to the event changes that we added to Lotus. Also there is some adjustment for the new lotus API version which has removed one of the methods that we rely on (`StateGetReceipt`)
=> chore: upgrade to lotus 1.8.0

chain/indexer.go, commands/lily.go, commands/watch.go, go.mod, go.sum, lens/lily/impl.go, lens/lily/struct.go, lens/lotus/api.go, lens/lotus/cachestore.go, lens/lotus/lotus.go, lens/lotusrepo/repo.go, lens/util/repo.go, lens/vector/repo.go, schedule/scheduler.go, testutil/lens.go
This only relates to the `visor run watch` command. When the rpc connection to the api was lost (e.g. Lotus restarting) the chain notifier job would close the event channel by calling Cancel but did not recreate it when the job was restarted. This left the watcher job with a permanently closed channel. 
Fix by not closing the channel between job restarts, but reuse it and send head events once connection to Lotus has been re-established.
Requires #490 to be merged first
Fixes #493
=> fix: improve reliability of reconnecting to lotus after disconnect

commands/daemon.go, commands/init.go, main.go
Splits out the import of a chain export into a separate command. This allows deployments to have external logic that controls when a repo should be initialised. For example in kubernetes we will have an init container that will run before the main container starts. The init container will write a marker file after import and then skip importing if the pod is restarted.
=> feat: add init command

schedule/scheduler.go
Fixing an error I entroduced in #501. We should only exit when __all__ scheduled jobs are complete.
=> fix(scheduler): only exit once all scheduled jobs complete

chain/indexer.go, lens/interface.go, lens/lily/impl.go, lens/lily/struct.go, lens/lotus/api.go, lens/lotusrepo/repo.go, lens/util/repo.go, lens/vector/repo.go, tasks/messages/message.go, tasks/msapprovals/msapprovals.go, testutil/lens.go
Fixes #426 by modifying and renaming `GetExecutedMessagesForTipset` -> `GetExecutedAndBlockMessagesForTipset` such that it returns a list of blocks and their corresponding messages, called `BlockMessages`, in addition to the executed messages. The `MessageProcessor` consumes the `BlockMessages` and populates the `block_messages` model with all messages in each block regardless of whether or not the message was executed (has a receipt) (this is the fix for #426). The `MessageProcessor` also populates the `message` model with a deduplicated set of aforementioned messages -- this ensures all messages from `block_messages` have an entry in `messages` model. 
If this change gets a :+1: I will regenerate the test vectors since this PR breaks them by changing the data read by the message …
=> fix(task): message task tracks unexecuted messages and their blocks

chain/indexer.go, lens/interface.go, lens/lily/impl.go, lens/lily/struct.go, lens/lotus/api.go, lens/lotusrepo/repo.go, lens/util/repo.go, lens/vector/repo.go, testutil/lens.go
- fix bug introduced in #491
where jsonrpc enforces 2 out params https://github.com/filecoin-project/go-jsonrpc/blob/45ea43ac2bec4c1134204bf0bf9ae7b9bc878fb9/util.go#L53
=> fix(api): jsonrpc only supports returning 2 params

tasks/messages/message.go
Ensures plain value transfers will appear in parsed_messages table. Currently they are skipped and an error is written to visor_processing reports `{"Error": "failed to parse message params: unknown method for actor type bafkqadlgnfwc6nbpmfrwg33vnz2a: 0"}`
=> fix: parse plain value transfer messages

go.mod, go.sum
v4 miner methods are not being parsed for parsed_messages table due to missing mapping in statediff. See https://github.com/filecoin-project/statediff/pull/219
=> fix: update statediff to include v4 miners

commands/daemon.go
we need to expand the config path before passing it to `config.EnsureExists`
=> fix(config): expand the config path when starting daemon

chain/indexer.go, commands/setup.go, lens/lily/impl.go
Converting head notifier channel into a buffered channel decouples the event subsystem from the indexer. Since this change I haven't seen the node fall out of sync.
=> fix: give head notifier a buffer

commands/setup.go, schedule/scheduler.go
Increase API cache size and remove restart delay if indexing takes too long. This reduces choppiness in the first few epochs when starting up visor against mainnet.
=> fix: increase API cache size

chain/indexer.go, chain/tipset.go, chain/watcher.go, lens/lily/impl.go, metrics/metrics.go, model/visor/report.go
During a watch, skip tipset processing if the indexer is taking longer than one epoch to process. We need to avoid blocking the stream of incoming tipsets otherwise we will cause the node to fall behind the chain while it waits for us to catch up (which may never happen if we consistently take too long)
=> fix: avoid indexer blocking head events

chain/tipset.go, chain/tipset_test.go, chain/watcher.go, commands/watch.go, metrics/metrics.go
Adds metrics that allows monitoring of the depth of the tipset cache and identification of reorgs that extend beyond the size of the cache. Also fixes the `watch_height` metric that was not being reported for lily. `watch_height` records the height of the most recent tipset event which may be an apply or a revert. Reorgs should be visible as a rapid reduction in this metric followed by a corresponding increase back to the expected epoch height.
=> feat: add metrics for tipset cache used by watches

chain/indexer.go, commands/daemon.go, lens/interface.go, lens/lily/impl.go, lens/lily/modules/statemanager.go, lens/lotus/api.go, lens/lotus/lotus.go, lens/lotusrepo/repo.go, lens/util/repo.go, lens/vector/repo.go, tasks/messageexecutions/message.go, tasks/messages/messageparams.go, testutil/lens.go
Implements internal message tracking for Cron Ticks and Miner Reward Messages.
=> Implement internal message task

metrics/metrics.go
This is not the first time we have forgotten to export a view by not adding it to the DefaultViews slice. So I made it harder to get wrong by defining the views directly in the slice.
=> fix: export watch_height metric

commands/job.go
None of our other options use uppercase and the job listing output uses lowercase for the id field.
=> polish: use lowercase for id option for consistency

commands/walk.go
Currently running `visor walk` starts a walk down the entire chain which is probably not what someone wants when trying out the command.
=> fix: make from and to options required for walk command

config/config.go, lens/lily/impl.go, storage/catalog.go, storage/csv.go, storage/csv_test.go
Add ability to embed name of job in csv filenames. This allows us to run multiple jobs without their files being overwritten by one another. We can also start jobs with meaningful names like `walk-975000-978000` and have output files named in the same way.
=> feat: add basic templating of csv filenames

chain/walker.go
Leftover from the very first version of visor's chain history task I think.
=> chore: remove unused finality field

chain/walker.go, chain/watcher.go, lens/lily/impl.go, schedule/scheduler.go
Also refactor how the params are surfaced to avoid hardcoding known jobs types in a type switch. Changed params map to have string values to make it simpler for clients to format result as a list or similar.
=> polish: include window and storage in job params output

tasks/messages/message.go
Commit 6f9f9998e6094d35cbb81796d5f4259b9b594971 introduced a bug that caused messages and block_messages rows to be written using the height of the receipt tipset instead of the tipset containing the message. This change fixes it by using the height directly associated with the message and/or block.
=> fix: record correct height for messages and block_messages

chain/indexer.go, chain/walker.go, chain/walker_test.go, chain/watcher_test.go, lens/util/repo.go, tasks/actorstate/task.go, tasks/consensus/task.go
Four changes:
1. actor tasks use parent height for processing report
2. reverse direction of consensus task processing so that processing report includes one for parent height
3. move single tipset processors into the indexer's parent/child loop and ensure they use the parent tipset only
4. start a walk at the tipset after upper bound height specified by `--to` so that the upper bound has a child tipset for context
Fixes https://github.com/filecoin-project/sentinel-visor/issues/652
=> fix: consistent processing report heights

chain/indexer.go, lens/lily/impl.go, lens/util/repo.go, tasks/messages/message.go, tasks/messages/message_test.go, tasks/messages/messageparams.go
We were reporting all message param parsing failures as errors in the processing report. However some messages simply have invalid parameters and failed to execute in the VM. Check this by looking at the exit code of the message and ignore the failure if the vm also failed to decode the parameters.
Note: the added test doesn't cover the ignore behaviour but documents the kind of failures we have seen in the wild.
Fixes #667, #666, #665, #664, #668, #663
~Also improves the error message reported by #660 but does not fix the underlying problem.~ Updated to also fix #660 by looking for actor in current state tree if not found in next.
PR is a little noisy because I renamed ts/pts arguments to next/current for clarity.
=> fix: avoid reporting processing error for malformed messages

README.md
the `--db` flag is a part of `lily migrate` - not lily
the command as is fails. 
Visor version:v0.7.7+16-gb048a53
=> Fix migrate command

storage/migrate.go
When running migrations over a partially completed schema, the base schema creation is being attempted again due to an incorrect check.
~I've also moved a defer closer to the lock it grabs to avoid held locks if base creation fails. This is probably never a concern as the schema wouldn't be shared without the base, but it would be annoying for the lock to be held from a prior failure and then deadlock waiting to apply patches. LMK if I'm misreading this.~ Removed.
fixes #706
=> Fix partial migration check

commands/daemon.go
makes all commands work as expect with the API flag set as opposed to the daemon flag only expecting a port and other commands expecting a full multiaddress.
Changes doesn't interfere with docs: https://github.com/filecoin-project/sentinel/blob/master/docs/lily/operation.md#api-endpoint
=> fix: daemon api uses full flag value

build/lily/docker.env, build/lily/docker_init.sh, docker-compose.yml
In order for users to quickly bootstrap lily completely within docker, I've added commented out stub and options to docker-compose setup.
Resolves https://github.com/filecoin-project/lily/pull/699#discussion_r728775964
=> chore(docker): Add lily stub/options for docker-compose

chain/walker_test.go, storage/sql_test.go
Breakage was caused by too short of timeouts, I am unsure what has caused their runtimes to increase in CI.
=> Fix CI and testing deadlines

chain/actors/builtin/init/diff.go, chain/actors/builtin/market/diff.go, chain/export/export.go, commands/util/rpc.go, lens/lily/modules/statemanager.go, lens/lily/struct.go, lens/util/repo.go, network/surveyer.go, tasks/actorstate/actorstate.go, tasks/chaineconomics/task.go, tasks/messages/message.go, tasks/survey/peeragents/peeragents.go
This consolidates logger names so we have fewer to manage. Since Lotus is very chatty we often set all logging to error level and selectively lower the level to info or debug for loggers of interest (for example: `--log-level=error --log-level-named=lily/chain:debug,lily/storage:debug,lily/schedule:debug,lens/util:debug,chain:info,badgerbs:info`). There were several loggers that logged only in one or two places but had their own obscure composite name (e.g. `lily/lens/lily`)
I've followed the general principle of naming loggers as `lily/` followed by the top level package name. This hopefully will be somewhat robust against refactoring inner packages over time.
The main exception is `lily/actors` which is found in the `chain/actors` package, but I think we ought to move that to its own …
=> chore: consolidate logger names

chain/walker_test.go, chain/watcher_test.go
Really weird and concerning this ever passed in CI but not locally.
This appears to be related to M1 macbooks and proof parameters
=> fix(tests): Ensembleminimal requires mocker proofs

chain/find.go, chain/find_test.go
fixes https://github.com/filecoin-project/lily/issues/773
fixes https://github.com/filecoin-project/lily/issues/775
=> fix(lily): Consider partially completed heights w ERRORs and SKIPs

.circleci/config.yml, Makefile, build/test-vectors/README.md, build/test-vectors/vectors.json, build/vector_params.go, commands/util/import.go, docker-compose.yml, go.mod, itests/builder.go, itests/fetch/fetch.go, itests/init.go, itests/node.go, itests/validators.go, itests/vector_test.go, storage/testing/storage.go
Revive vector tests - this PR adds the logic for testing lily via test vectors!
Add a vector to `build/test-vectors/vectors.json`, see `build/test-vectors/README.md` for instruction on how to do this
Right now we only have vectors from the calibration network. Mainnet vectors can be added later with no modification to the test suite. 
When executing `make itest-calibration` for the follow occurs:
1. Vectors are downloaded (based on`vector.json`) to `/var/tmp/lily-test-vectors/<network_name>`. If the vector files are cached their contents is simply validated.
2. Ensure the expected vectors are present on the filesystem, failing the test suite otherwise.
3. Connect to timescale instance, migrating to the latest version if required.
4. Construct a full in-memory lily node, configured to talk …
=> Generic in memory lily testing via vectors

.circleci/config.yml, Makefile, go.mod, go.sum, support/tools/go.mod
need this to land https://github.com/filecoin-project/lily/pull/821 since it uses reflection calls added in 1.17.
=> deps: update to go1.17.6

storage/csv.go
Needed so that sentinel archiver can write/verify the correct headers for the csv output it is working with
=> polish: add method to get csv headers for model

.circleci/config.yml, .dockerignore, Makefile, build/docker/builder.tpl
Building the lily binary within the docker context makes the build
version always "dirty". This is because dockerignore omits files
from the build context which are committed into the git repo. When
these files are missing, git considers that repo "dirty".
This change allows the Makefile to use LILY_VERSION to set the build
version of the lily binary. This value used as an envvar within the
docker build environment which overrides the default ("dirty")
LILY_VERSION with the version perceived by git before dockerignore
filters/removes files from the build.
=> fix(docker): Docker image build versions are no longer "dirty"

.circleci/config.yml, build/docker/prod_entrypoint.tpl
=> fix(docker): Update docker base image for prod; Fix libc mismatch

chain/indexer.go
=> fix: error marshalling in processing reports

main.go
This PR sets the default log level to `info` instead of `debug`.
Resolves #703
=> Set default log level to info. Resolves #703

chain/indexer.go, tasks/actorstate/account.go, tasks/actorstate/account_test.go, tasks/actorstate/actor.go, tasks/actorstate/actor_test.go, tasks/actorstate/actorstate.go, tasks/actorstate/actorstate_test.go, tasks/actorstate/init.go, tasks/actorstate/init_test.go, tasks/actorstate/market.go, tasks/actorstate/market_test.go, tasks/actorstate/miner.go, tasks/actorstate/multisig.go, tasks/actorstate/multisig_test.go, tasks/actorstate/power.go, tasks/actorstate/power_test.go, tasks/actorstate/reward.go, tasks/actorstate/reward_test.go, tasks/actorstate/task.go, tasks/actorstate/verifreg.go, tasks/messageexecutions/message.go, tasks/messages/message.go, tasks/messages/message_test.go, tasks/msapprovals/msapprovals.go
This PR targets the `indexer-refactor` branch.
This PR aims to keep indexer behavior consistent with the current while landing some refactor work to improve code extensibility.
- embed `GetExecutedAndBlockMessagesForTipset` in processors, preventing unnecessary (and expensive!) calls to the method when its output isn't used. And example of this would be running all actor tasks excluding the miner actor. Prior changes [here](https://github.com/filecoin-project/lily/pull/849/files#diff-88c7f968b3518b2c701d948daf6e103fdc0b57c3525a8e24f19645ae5c1d74c6R96-R115) ensure multiple calls to this method are only executed once, returning a cached value for subsequent calls. This change also makes the indexer's logic more concise.
- embed `GetMessageExecutions` in processors, taking advantage of the …
=> setup for indexer refacor

commands/log.go, lens/lily/api.go, lens/lily/impl.go, lens/lily/struct.go
lets you do things like:
`lily log set-level error` // set all loggers to error level
`lily log set-level-regex info 'lily/*'` // set all lily loggers (since we follow the `lily/<logname>` convention) to info
=> feat: set log level with regular expression

.circleci/config.yml, Dockerfile, Dockerfile.dev, Makefile, build/docker/builder.tpl
This PR enables continuous delivery triggers into our infrastructure repos. There are a few changes included:
- separate docker image publishing into parallel jobs
- fix calibnet and butterflynet docker builds
- docker image builds trigger on
- tags containing `dev`
- branch names containing `deploy`
- include job which triggers the pipeline in the infra repo. Deployments trigger on
- tags containing `dev`
- branch names containing `deploy`
=> feat(ci): Continuous deployment for tags and deploy branches

model/actors/miner/task.go, tasks/actorstate/miner.go
This change is required to prevent nil models from the `actorstatesminer` task from being persisted, e.g.:
```
{"level":"error","ts":"2022-02-25T20:45:10.165Z","logger":"lily/chain","caller":"chain/indexer.go:506","msg":"persistence failed","current":725047,"next":725048,"task":"actorstatesminer","error":"persisting model: pg: Model(nil)","errorVerbose":"persisting model:\n    github.com/filecoin-project/lily/storage.(*TxStorage).PersistModel\n        /go/src/github.com/filecoin-project/lily/storage/sql.go:428\n  - pg: Model(nil)"}
```
was found in calibnet staging
=> fix: persisting miner task results with nil models

lens/util/repo.go
```go
switch t.Kind() {
case reflect.Ptr:
// unwrap pointer
v = v.Elem()
t = t.Elem()
fallthrough
case reflect.Struct:
// if its a struct, walk its fields and recurse.
...
```
Fallthrough will execute the action in next case regardless of the condition.
`case reflect.Struct` will be executed even if the pointee of a pointer is not a Struct.
```go
package main
import (
"fmt"
)
func main() {
eval := func() int {
fmt.Println("eval")
return 2
}
switch {
case 1 == 1:
fmt.Println("1 == 1")
fallthrough
case eval() == 1:
fmt.Println("2 == 1")
}
}
````
Output:
```
1 == 1
2 == 1
```
[Go Playground](https://go.dev/play/p/t_RbGHPCnd7)
=> fix: wrong use of fallthrough in marshalling paramWrapperType

lens/util/repo.go
I don't know if this will actually parse the params correctly, need to verify still, but it will at least prevent the daemon from panicing and return a more helpful error message.
- fixes #887
=> fix: avoid panic on reflected param parsing code

lens/util/repo.go, tasks/messages/message_test.go
- fixes #892
parsed_messages after apply this fix:
```
+--------------------------------------------------------------+------+--------------------------------------------------------------------------------------+-----------------------------------------+-----+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|cid                                                           |height|from …
```
=> fix: avoid custom marshal for zero and invalid values

.circleci/config.yml
This fixes some edge cases with the autodeploy regex trigger. See:
- testing branch deploy: https://app.circleci.com/pipelines/github/filecoin-project/lily/3248
- testing RC tag deploy: https://app.circleci.com/pipelines/github/filecoin-project/lily/3249
- testing dev tag deploy: https://app.circleci.com/pipelines/github/filecoin-project/lily/3250
And actual deployment of this branch: https://app.circleci.com/pipelines/github/filecoin-project/lily/3251.
Reminder:
- branches trigger when `deploy` is in the name
- tags trigger for these forms: vN.N.N, vN.N.N-rcN, or vN.N.N-dev (no additional letters allowed)
(Follow-on fix from https://github.com/filecoin-project/lily/pull/868)
=> chore(ci): Adjust comments; Fix autodeploy regexs

Makefile
Cleaning Dockerfiles now have their own make target `make docker-clean` and are no longer included in `make clean`.
=> chore: Dockerfiles are no longer included in `make clean`

tasks/actorstate/miner.go
=> fix: track dealID's of snapped sector

chain/actors/builtin/miner/diff.go, tasks/actorstate/miner/precommit.go, tasks/actorstate/miner/sector.go, tasks/actorstate/miner/sector_deals.go, tasks/actorstate/miner/sector_events.go, tasks/actorstate/miner/sectorv7.go
Note: This PR targets indexer-refactor branch
- fixes #897
- simply miner extractor logic
- ensure snapped sector dealID's are recorded by SectorDealsExtractor
=> fix: loading miner actor when actor doesn't exist

commands/export.go, commands/gap.go, commands/walk.go
=> fix: return error when to and from are invalid

lens/util/repo.go, tasks/messages/message_test.go
=> fix(schema): Rollback v15 ProveCommitAggregate param schema to match 

metrics/metrics.go
Allow to create dashboard trakcking height per job.
=> Add job name to TipsetHeight metric

storage/migrate.go, storage/sql.go
=> fix: prevent lily from running with incompatible schema

commands/help.go
- `help models-list` comments are limited to 80 chars
=> chore(help): Adjust help models-list width

lens/lily/impl.go, schedule/scheduler.go
=> fix: job wait respects Ctrl-C

commands/job/fill.go, commands/job/find.go, commands/job/index.go, commands/job/survey.go, commands/job/walk.go, commands/job/watch.go
closes #969
Ideally, this check would be performed once in a `job run` `Before` [option](https://github.com/filecoin-project/lily/blob/master/commands/job/job.go#L27), but that would break the `survey` command since it uses different task names. This is making me rethink if the `survey` job should go somewhere else. Thoughts?
=> chore: reject invalid tasks on client

chain/walk/walker_test.go, testutil/filtypes.go
- reduce the requirements for running test
I have noticed this test [flakes sometimes](https://app.circleci.com/pipelines/github/filecoin-project/lily/3536/workflows/6ef9122e-0372-4bd6-8041-0c6505b958d3/jobs/15593). On the off chance this is a race condition within Postgres I have removed it as a dependency of the test opting to use an in-memory storage type instead.
=> chore: walk test uses in memory storage

commands/sync.go
I frequently have to stop a Lily daemon manually when I do backfills or partial repository archiving work. Until filecoin-project/lotus#8641 is ready, I need to be able to have a way to determine what the latest height is.
~~This PR accepts a string flag to the `stop` command that determines at the most recent height the given stage stopped. This allows me to use the height in `stdout` to be used as an input for next steps in the data pipeline.~~
It accepts a bool flag to `sync` called `output` that would enable me to continuously poll the sync command with simple bash one-liners and check at what stage and what height it currently is at.
e.g.
```
❯ ./lily sync status --output="text"
2022-06-27T13:11:35.035+0200    WARN    cliutil util/apiinfo.go:81      API Token not set and requested, …
```
=> chore: add output flag to sync status command

chain/indexer/distributed/queue/tasks/gapfill.go, chain/indexer/distributed/queue/tasks/index.go
=> fix: allow tasks to be retired with block not found

tasks/actorstate/miner/context.go, tasks/actorstate/miner/deadline_info.go, tasks/actorstate/miner/fee_debt.go, tasks/actorstate/miner/locked_funds.go, tasks/actorstate/multisig/multisig.go, tasks/actorstate/power/power.go, tasks/actorstate/verifreg/verifreg.go
fixes #1017 
- the hardest of facepalms
=> fix: many incorrect pointer equality comparisons

commands/chain.go
```$ lily chain actor-codes```
```
+---------+------------+--------+----------------------------------------------------------------+
| VERSION | NAME       | FAMILY | CODE                                                           |
+---------+------------+--------+----------------------------------------------------------------+
|       0 | fil/1/init | init   | bafkqactgnfwc6mjpnfxgs5a                                       |
+---------+------------+--------+----------------------------------------------------------------+
|       2 | fil/2/init | init   | bafkqactgnfwc6mrpnfxgs5a                                       |
+---------+------------+--------+----------------------------------------------------------------+
|       3 | fil/3/init | init   | bafkqactgnfwc6mzpnfxgs5a …
```
=> feat: command to print actor CID's and version

commands/chain.go, lens/lily/impl.go
- state list outputs JSON
- all commands under `state-*` prefix
- fix bug in `for` loop breaking on null rounds
=> chore: Some UX around the `chain state-*` commands

commands/chain.go, lens/lily/api.go, lens/lily/impl.go, lens/lily/struct.go
This PR adds 4 new commands to the chain command.
Finds the range of states lily has a complete state tree for:
```
$ lily chain find-oldest
Newest:
StateRoot:	1830000
Messages:	1830000
Oldest:
StateRoot:	1828199
Messages:	1828199
```
Lists all states lily has and their completeness:
``` 
$ lily chain list-state --limit=1829989
+---------+-----------+----------+
|  HEIGHT | STATETREE | MESSAGES |
+---------+-----------+----------+
| 1830000 | true      | true     |
+---------+-----------+----------+
| 1829999 | true      | true     |
+---------+-----------+----------+
| 1829998 | true      | true     |
+---------+-----------+----------+
| 1829997 | true      | true     |
+---------+-----------+----------+
| 1829996 | true      | true     |
+---------+-----------+----------+
| 1829995 | …
```
=> feat: add method for finding oldest state and computing state

build/grafana/provisioning/datasources/datasource.yml, build/lily/docker_init.sh, build/lily/notifier.env, build/lily/notifier_config.toml, build/lily/redis-queue.env, build/lily/worker.env, build/lily/worker_config.toml, build/prometheus/prometheus.yml, docker-compose.yml
Closes #1034 
- remove `daemon` and replace w `notifier` and `worker` containers
- `notifier` and `worker` each have it's own envvars and config
- redis instance is brought up first and both `notifier` and `worker` successfully register their queues
- prometheus should be target scraping both though I haven't tested it (or jaeger/tasks as I don't have a repo handy)
=> feat(docker): Update docker-compose to use lily worker pattern

chain/datasource/datasource.go, chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, go.mod, lens/interface.go, lens/lily/impl.go, lens/lily/struct.go, lens/util/repo.go, tasks/actorstate/actorstate.go, tasks/actorstate/miner/post.go, tasks/api.go, tasks/messages/blockmessage/task.go, tasks/messages/gaseconomy/task.go, tasks/messages/gasoutput/task.go, tasks/messages/message/task.go, tasks/messages/parsedmessage/task.go, tasks/messages/receipt/task.go, tasks/msapprovals/msapprovals.go, tasks/test/api.go, testutil/lens.go
This PR removes the `ExecutedAndBlockMessages` method and replaces it smaller more specific methods: `TipSetMessageReceipts`, `TipSetBlockMessages`, and `ComputeGasOutputs`. 
While implementing, I noticed a few bugs in the now replaced `ExecutedAndBlockMessages` method, which are tracked in #1045 and #1043 and fixed in this PR. Furthermore, I took the opportunity to address #1041 while implementing `TipSetMessageReceipts`.
=> Replace ExecutedAndBlockMessages with individual methods

tasks/actorstate/miner/sector_events.go
=> fix: prevent MinerSectorEvent panic on empty SectorStateEventso

itests/fetch/fetch.go
use the web3 storage gateway to ensure vectors are always downloaded successfully. dweb gateway fails to serve content.
=> fix: use web3.storage gateway

tasks/messages/parsedmessage/task.go
=> fix: removed unused gas calc from parsedmessages

lens/util/repo.go, tasks/messageexecutions/vm/task.go
=> fix: handle vm message param and return parsing

tasks/actorstate/miner/sector_events.go
Using bitfield.MultiMerge once instead of bitfield.MergeBitFields repeatedly should reduce the time by 50%.
=> fix: Use bitfield.MultiMerge to improve LoadSectorState performance

lens/lily/impl.go, lens/util/repo.go, tasks/messageexecutions/vm/task.go, tasks/messages/gasoutput/task.go, tasks/messages/parsedmessage/task.go, tasks/msapprovals/msapprovals.go
Without actor code mapping, MakeGetActorCodeFunc & all GetActorCode calls only take a few ms to execute.
Time to construct actor code mapping with 5M state store caching takes ~10s.
Time to construct actor code mapping without caching takes ~40s.
=> fix: remove actor code mapping

.circleci/config.yml
CI is not triggering this job. In this, I try again by switching to a text matcher.
=> fix(ci): Use a string matcher for the workflow

Dockerfile, build/docker/prod_entrypoint.tpl
closes https://github.com/filecoin-project/sentinel-infra/issues/408
Note the tradeoff here is a larger image (going from ~300MB to ~700MB) in exchange for shorter startup time and avoidance of potential future issues related to transient proof downloads.
(This also means that proof changes will require a new build/release.)
=> chore(docker): Cache proof params in production docker image

tasks/messageexecutions/vm/task.go
=> fix: only parse vm messages with exit code OK

chain/gap/fill.go, chain/walk/walker.go, chain/walk/walker_test.go, chain/watch/watcher.go, chain/watch/watcher_test.go, lens/lily/api.go, lens/lily/impl.go, schedule/scheduler.go
The json returned by lily job list should include current height for walk, watch and gapfill jobs.
Add the `currentHeight` in `Reporter`, then pass the `Reporter` to Watcher, Walker and Filler. Therefore, they can update the `currentHeight` during job execution. Finally, we could see the current height for walk, watch and gapfill jobs.
=> [command] add currentheight to job list

lens/util/repo.go, model/messages/vm.go, schemas/v1/13_vm_messages_index.go, tasks/messageexecutions/vm/task.go
=> fix: add index column constraint to vm_messages table

commands/net.go, lens/lily/api.go, lens/lily/struct.go
Allows the user to instruct lily to connect and disconnect from peers on the network.
=> feat: add logic for connecting and disconnecting from peers

chain/datasource/datasource.go, lens/interface.go, tasks/api.go, tasks/messages/actorevent/task.go
- it handles the case of legacy events
=> fix: use builtin lotus method to get events

lens/util/store.go, metrics/metrics.go
Gives us metrics like:
```
visor_state_store_cache_hits 8.774107e+06
visor_state_store_cache_limit 500000
visor_state_store_cache_read 1.7223509e+07
visor_state_store_cache_size 500000
```
and
```
visor_block_store_cache_hits 254849
visor_block_store_cache_limit 500000
visor_block_store_cache_read 8.760208e+06
visor_block_store_cache_size 500000
```
=> feat: metrics for state & block store caches

chain/actors/builtin/verifreg/actor.go.template, chain/actors/builtin/verifreg/state.go.template, chain/actors/builtin/verifreg/v0.go, chain/actors/builtin/verifreg/v10.go, chain/actors/builtin/verifreg/v2.go, chain/actors/builtin/verifreg/v3.go, chain/actors/builtin/verifreg/v4.go, chain/actors/builtin/verifreg/v5.go, chain/actors/builtin/verifreg/v6.go, chain/actors/builtin/verifreg/v7.go, chain/actors/builtin/verifreg/v8.go, chain/actors/builtin/verifreg/v9.go, chain/actors/builtin/verifreg/verifreg.go, chain/diff/actor.go, chain/diff/map.go, chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, chain/indexer/tasktype/table_tasks.go, chain/indexer/tasktype/tasks.go, chain/indexer/tasktype/tasks_test.go, model/actors/verifreg/claims.go, schemas/v1/17_verifreg_claims.go, storage/sql.go, tasks/actorstate/verifreg/claims.go
- request made here: https://github.com/protocol/pldw/issues/177#issuecomment-1372920524
=> feat: track verifreg actor claim HAMT changes

chain/datasource/datasource.go, metrics/metrics.go
=> fix: correctly diff new actor version

lens/util/repo.go
```
persist result (vm_messages.model.PersistableList): persisting model.PersistableList:
persisting model: ERROR #22P02 invalid input syntax for type json
```
at epoch: 2683598. We will get the issue during inserting the empty string params, returns as jsonb type in PostgreSQL.
=> fix: Fix the error jsonp format in vm_message

lens/util/repo.go
It will cause the error in PostgreSQL: `unsupported Unicode escape sequence`
Therefore, we have to fix it.
=> fix: Add function for cleaning the Unicode escape sequence

lens/util/repo.go, tasks/messages/message_test.go
Don't error on unknown method numbers for FEVM.
Due to the [previous fix](https://github.com/filecoin-project/lily/pull/1165/files), it will return the `Unknown` method, then cause the error in `parsed_message`.  Therefore, we can use the same logic as `vm_message`: logging the error without returning error.
=> fix: log unknown actor type without returning error

model/actors/common/actors.go, schemas/v1/20_actor_add_state.go, schemas/v1/21_actor_add_state.go, tasks/actorstate/raw/actor.go
Based on the information provided, it appears that the `actor_states` table is being deprecated because the data it contains is mostly covered by the `actors` table. However, there are two columns: `state` and` code_cid`, which are present in `actor_states` but missing in `actors`. To address this, these two columns will be added to the `actors` table, thereby making the `actor_states` table redundant. Once this is done, the `actor_states` table can be safely deprecated.
=> feat: Add the state and code_cid for actors table

deployment/lily/config.toml
Using the `AddrEnv = "LILY_REDIS_ADDR"` instead of using hard code address in config.toml.
=> fix: using the env variable for lily redis

chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, tasks/actorstate/raw/actor.go, tasks/actorstate/raw/actor_state.go, tasks/actorstate/task.go
Currently, actor state changes are stored as `model.PersistableList`, which doesn't support batch persistence. This PR adds  a transformer to actorstate task to convert `model.PersistableList` to corresponding model type that supports batch persistence.
This resolves #1190.
=> fix: batch insert actor & actor_state data

model/actors/common/actors.go
CSVs produced follow the order of the definition in the model. So CSVs of `actors` produced with this model definition are ordered like so:
```
height,id,state_root,code,code_cid,head,balance,nonce,state
```
This is problematic when inserting CSVs to other data sources as one then has to create these two columns before the change is introduced and fill these `null` values manually (really only a problem for `code_cid` which is in the middle of the table).
Note that Postgres doesn't have this issue (new columns are appended at the end).
=> fix: CodeCID should be at end of model

chain/walk/walker.go, chain/walk/walker_test.go, commands/job/job.go, commands/job/options.go, lens/lily/api.go, lens/lily/impl.go
This pull request can resolve the issue: https://github.com/filecoin-project/lily/issues/1210.
By default, when the stopOnFatalError flag is set to false, the process will continue from start to end without halting, regardless of any errors encountered.
To turn on the flag: `--stop-on-error=true`
```
./lily job run --storage=CSV --tasks="fevm_block_header"  --stop-on-error=true walk --from=566400 --to=566405
```
=> feat: add new option for walk config

chain/indexer/integrated/manager.go, chain/indexer/integrated/manager_test.go, chain/indexer/integrated/tipset/tipset.go
The channel will become blocked once it reaches its full capacity.
=> fix: resize error channel

Makefile
related docs: https://github.com/filecoin-project/sentinel/pull/235
=> chore: do not require mac users to preset env vars

chain/actors/adt/diff/generic.go, chain/actors/builtin/init/diff.go, chain/actors/builtin/market/diff.go, chain/actors/builtin/miner/diff.go, chain/actors/builtin/miner/diff_v8.go, chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, chain/indexer/tasktype/table_tasks.go, chain/indexer/tasktype/tasks.go, chain/indexer/tasktype/tasks_test.go, storage/sql.go, tasks/actorstate/miner/precommit.go
For earlier parts of the chain, i.e. when miner actors were v8 and below, we get the following error:
```
{
"level": "warn",
"ts": "2023-07-06T00:03:04.875Z",
"logger": "lily/tasks",
"caller": "actorstate/task.go:140",
"msg": "failed to transform with error: ",
"error": "expected MinerPreCommitInfoV9List type but got: miner.MinerPreCommitInfoList"
}
```
=> fix: add Transform implementation for PreCommitInfoExtractorV8

lens/util/repo.go
Resolve the unnecessary warning log that occurs when parsing internal messages (`vm_message`, `fevm_traces`). https://github.com/filecoin-project/lily/issues/1235
=> feat: change the logging condition for parsing internal message

model/fevm/trace.go, schemas/v1/28_add_actor_names_to_fevm_traces.go, tasks/fevm/trace/task.go
This feature adds human-readable actor codes for sender and receiver to fulfill an offline request via Slack from @ychiaoli18.
This should make queries necessary for the FEVM analyses faster as it will no longer require merges with the actors table.
=> feat: add human readable actor codes in fevm_traces

tasks/fevm/trace/task.go
The root cause for the incorrect `eth_address` was due to passing the actor ID as the actor address into the function, leading to a misinterpretation of the `eth_address`. Therefore, once we obtained the correct actor address, we resolved this issue.
=> fix: align the eth address in fevm trace

chain/indexer/integrated/processor/state.go
If there is no `periodicActorDumpProcessors` in the watch or walk, then we do not have to run the `StateListActors`.
=> fix: skip StateListActors if there is no actor dump processor

deployment/prefect/config.toml
In order to centralize the `config.toml` of related services, the decision was made to store the `config.toml` within the deployment folder.
=> feat: add new config to prefect service

model/fevm/trace.go, schemas/v1/30_fevm_actor_dumps.go, schemas/v1/32_change_the_fevm_trace_pkey.go
Try to make the `fevm_trace`' primary key be more simple and unique.
=> chore: Change the pkey of fevm_traces and refine the previous migration script

model/fevm/transaction.go
Remove the redundant `pk` in fevm_transactions table.
=> fix: remove the typo in fevm transactions model

chain/datasource/datasource.go, chain/indexer/integrated/processor/state.go, chain/indexer/tasktype/table_tasks.go, chain/indexer/tasktype/tasks.go, chain/indexer/tasktype/tasks_test.go, lens/interface.go, model/actordumps/miner_actor_dump.go, schemas/v1/33_miner_actor_dumps.go, storage/sql.go, tasks/api.go, tasks/periodic_actor_dump/miner_actor/tasks.go
We have implemented a miner actor dump task, which allows us to comprehensively inspect the current status of miners and easily analyze the historical behavior of a specific miner.
Use the `StateLookupRobustAddress` to get the miner address.
=> feat: add new actor dump: miner

model/actordumps/miner_actor_dump.go
Fix the peer_id column in `miner_actor_dumps` table from bytes to text.
=> fix: the peer_id encode error

commands/sync.go, commands/util.go, lens/lily/api.go, lens/lily/struct.go, model/blocks/unsynced_header.go, schemas/v1/33_unsynced_block_headers.go, schemas/v1/34_unsynced_block_headers.go
This command allows users to monitor the occurrence frequency of orphan blocks in real-time, providing insights into the health status of the blockchain or for post-analysis purposes.
=> feat: add new job to find out orphan block

chain/datasource/datasource.go, lens/interface.go, lens/lily/impl.go, tasks/api.go, tasks/messages/gaseconomy/task.go, testutil/lens.go
To address the data mismatch problem in `message_gas_economy`, we will rectify the data by utilizing the `BlockMsgsForTipset` function to obtain a valid list of CIDs. Subsequently, we will rerun the same process, incorporating an improved filtering function designed to exclude any invalid CIDs from the analysis.
Try to resolve the issue: https://github.com/filecoin-project/lily/issues/1266
=> feat: Add new function for filtering invalid message

chain/datasource/datasource.go, chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, chain/indexer/tasktype/table_tasks.go, chain/indexer/tasktype/tasks.go, chain/indexer/tasktype/tasks_test.go, go.mod, go.sum, lens/interface.go, lens/lily/api.go, lens/lily/impl.go, lens/lily/struct.go, model/actors/builtinactor/builtinactorevents.go, schemas/v1/36_builtin_actor_event.go, storage/sql.go, tasks/api.go, tasks/messages/builtinactorevent/task.go
Add the `builtin-actor-event` task.
Need to run the migration script
```
lily migrate --db="postgres://{user}:{password}@{host}:{port}/lily?sslmode=disable" --name migration --schema {schema} --to 1.36
```
Modify the config to get the `builtin_actor_event`.
```
[Events]
EnableActorEventsAPI = true
```
- https://fips.filecoin.io/FIPS/fip-0083.html
- https://github.com/rvagg/FIPs/blob/0986a7bf43ed3101bf73bd2a289ae689d8882dee/FIPS/fip-0083.md
=> feat: add builtin-actor-event task

model/actors/builtinactor/builtinactorevents.go, schemas/v1/37_change_pkey_builtin_actor_event.go, tasks/messages/builtinactorevent/task.go
Add a new column for `builtin_actor_events`: `event_idx`. Moreover, add more index for `builtin_actor_events`. Then covert it into hypertable.
```
lily migrate --db="postgres://{user}:{password}@{host}:{port}/lily?sslmode=disable" --name migration --schema {schema} --to 1.37
```
=> feat: add new column for builtin_actor_events

go.mod, tasks/messages/builtinactorevent/task.go
There is an error during the parsing the cid in `builtin_actor_events`.
```
ERROR	lily/tasks/builtinactorevent	builtinactorevent/task.go:158	cbor.Unmarshal err: invalid cid: invalid cid: expected 1 as the cid version number, got: 0, key: piece-cid, value: [216 42 88 40 0 1 129 226 3 146 32 32 228 70 102 200 187 252 1 84 224 140 131 94 192 12 79 75 10 106 245 208 197 80 239 236 194 115 180 86 152 152 84 41]
```
Use the recommended library to parse it: https://github.com/ipld/go-ipld-prime.
=> fix: use the new library to parse cid from builtin_actor_event

chain/actors/builtin/market/actor.go.template, chain/actors/builtin/market/market.go, chain/actors/builtin/market/state.go.template, chain/actors/builtin/market/v0.go, chain/actors/builtin/market/v10.go, chain/actors/builtin/market/v11.go, chain/actors/builtin/market/v12.go, chain/actors/builtin/market/v13.go, chain/actors/builtin/market/v2.go, chain/actors/builtin/market/v3.go, chain/actors/builtin/market/v4.go, chain/actors/builtin/market/v5.go, chain/actors/builtin/market/v6.go, chain/actors/builtin/market/v7.go, chain/actors/builtin/market/v8.go, chain/actors/builtin/market/v9.go, chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, chain/indexer/tasktype/table_tasks.go, chain/indexer/tasktype/tasks.go, chain/indexer/tasktype/tasks_test.go, model/actors/miner/sectordealsV2.go, schemas/v1/38_miner_sector_info_v2.go, storage/sql.go, tasks/actorstate/market/sector_deals_v2.go, tasks/messages/builtinactorevent/task.go
Add the `miner_sector_deal_v2` task.
Due to the critical change in nv22 upgrade:[Deprecate Deal IDs](https://github.com/filecoin-project/builtin-actors/pull/1402) in sector info. Therefore we are going to use the new column: [provider_sectors](https://github.com/filecoin-project/builtin-actors/blob/a0e34d22665ac8c84f02fea8a099216f29ffaeeb/actors/market/src/state.rs#L88) in Market Actor.
Need to run the migration script
```
lily migrate --db="postgres://{user}:{password}@{host}:{port}/lily?sslmode=disable" --name migration --schema {schema} --to 1.38
```
=> feat: add new task miner sector deal v2

tasks/messages/builtinactorevent/task.go
Refine the `Fields` in GetActorEventsRaw filtering.
=> feat: Refine the filter for the GetActorEventsRaw

chain/actors/builtin/market/actor.go.template, chain/actors/builtin/market/market.go, chain/actors/builtin/market/state.go.template, chain/actors/builtin/market/v0.go, chain/actors/builtin/market/v10.go, chain/actors/builtin/market/v11.go, chain/actors/builtin/market/v12.go, chain/actors/builtin/market/v13.go, chain/actors/builtin/market/v2.go, chain/actors/builtin/market/v3.go, chain/actors/builtin/market/v4.go, chain/actors/builtin/market/v5.go, chain/actors/builtin/market/v6.go, chain/actors/builtin/market/v7.go, chain/actors/builtin/market/v8.go, chain/actors/builtin/market/v9.go, lens/util/builtinactor.go, tasks/actorstate/market/sector_deals_v2.go
`ProviderSectors` is a nested HAMT structure, therefore it is hard to do the reversed search from dealID to ProviderID. It make the performance issue for `miner_sector_deal_v2`.
Use the new field: `SectorNumber` in `DealState` and combine with `market.Proposals` to refine the performance of `miner_sector_deal_v2`.
=> feat: refine miner_sector_deal_v2 performance issue

tasks/messages/builtinactorevent/task.go
The `builtin_actor_event` task took more than 30s in several epochs at 512G memory machine. Moreover, sometime we would miss the builtin_actor_events from api.
1. Remove the filter for fields and more the filtering function in task code.
2. Add the message execution then it could trigger the function to collect builtin_actor_events.
=> feat: refactor builtin actor event

model/actors/datacap/state.go, model/chain/economics.go, schemas/v1/39_add_locked_fil_v2_chaineconomics.go, tasks/actorstate/datacap/balance.go, tasks/chaineconomics/economics.go, tasks/chaineconomics/economics_test.go
Need to run the migration script
`lily migrate --db="postgres://{user}:{password}@{host}:{port}/lily?sslmode=disable" --name migration --schema {schema} --to 1.39`
=> feat: add new column for locked_fil_v2 in chain_economics and address_type in data_cap_balances

chain/indexer/integrated/processor/state.go, chain/indexer/integrated/processor/state_internal_test.go, chain/indexer/integrated/processor/state_test.go, chain/indexer/tasktype/table_tasks.go, chain/indexer/tasktype/tasks.go, chain/indexer/tasktype/tasks_test.go, model/chain/economics.go, model/chain/economics_v2.go, schemas/v1/40_add_chaineconomics_v2.go, storage/sql.go, tasks/chaineconomics/economics.go, tasks/chaineconomics/economics_v2.go, tasks/chaineconomics/task.go
Need to run the migration script
```
lily migrate --db="postgres://{user}:{password}@{host}:{port}/lily?sslmode=disable" --name migration --schema {schema} --to 1.40
```
=> feat: add new table for nv23
